import { createContext, useContext, ReactNode } from "react";

interface LanguageContextType {
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<string, string> = {
    // Navigation
    "nav.home": "Home",
    "nav.challenges": "Challenges",
    "nav.feed": "Feed",
    "nav.leaderboard": "Leaderboard",
    "nav.profile": "Profile",
    "nav.wallet": "Wallet",
    "nav.referrals": "Referrals",
    "nav.admin": "Admin Panel",
    "nav.signOut": "Sign Out",
    "nav.signIn": "Sign In",
    "nav.getStarted": "Get Started",
    
    // Hero Section
    "hero.badge": "Join 100k+ Creators Worldwide",
    "hero.title1": "Create.",
    "hero.title2": "Compete.",
    "hero.title3": "Win Big.",
    "hero.description": "Join daily creative challenges, earn points and badges, compete with creators worldwide, and win real cash prizes. Your creativity has never been this rewarding!",
    "hero.cta": "Start Creating Now",
    "hero.howItWorks": "See How It Works",
    "hero.prizesWon": "Prizes Won",
    "hero.activeUsers": "Active Users",
    "hero.challenges": "Challenges",
    
    // Stats
    "stats.totalPrizes": "Total Prizes",
    "stats.awardedToCreators": "Awarded to creators",
    "stats.activeCreators": "Active Creators",
    "stats.creatingDaily": "Creating daily",
    "stats.dailyChallenges": "Daily Challenges",
    "stats.newEveryDay": "New every day",
    "stats.avgEarnings": "Avg Earnings",
    "stats.perMonth": "Per month",
    
    // Challenges
    "challenges.featured": "Featured Challenges",
    "challenges.trending": "Join these trending challenges and start earning today",
    "challenges.joinChallenge": "Join Challenge",
    "challenges.participants": "Participants",
    "challenges.timeLeft": "Time Left",
    "challenges.prize": "Prize",
    "challenges.points": "Points",
    "challenges.difficulty": "Difficulty",
    "challenges.easy": "Easy",
    "challenges.medium": "Medium",
    "challenges.hard": "Hard",
    
    // CTA
    "cta.title": "Ready to Turn Your Creativity Into Cash?",
    "cta.description": "Join thousands of creators earning money doing what they love. Sign up now and get 100 bonus points!",
    "cta.button": "Join Questify Free",
    
    // Auth
    "auth.login": "Login",
    "auth.signup": "Sign Up",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.username": "Username",
    "auth.displayName": "Display Name (Optional)",
    "auth.signIn": "Sign In",
    "auth.signInWith": "Or continue with",
    "auth.createAccount": "Create Account",
    "auth.signingIn": "Signing in...",
    "auth.creatingAccount": "Creating account...",
    
    // Referrals
    "referrals.title": "Referral Program",
    "referrals.description": "Invite friends and earn rewards together! Get 50 points for each friend who joins, and they get 25 points.",
    "referrals.totalReferrals": "Total Referrals",
    "referrals.totalEarnings": "Total Earnings",
    "referrals.rewardPerReferral": "Reward Per Referral",
    "referrals.yourCode": "Your Referral Code",
    "referrals.shareCode": "Share this code with friends to earn rewards",
    "referrals.copyLink": "Copy Link",
    "referrals.share": "Share",
    "referrals.shareOnSocial": "Share on social media",
    "referrals.howItWorks": "How it works:",
    "referrals.step1": "Share your referral code or link with friends",
    "referrals.step2": "They sign up using your code and get 25 bonus points",
    "referrals.step3": "You receive 50 points for each successful referral",
    "referrals.history": "Referral History",
    "referrals.noReferrals": "No referrals yet",
    "referrals.startSharing": "Share your referral code to start earning rewards!",
    "referrals.joined": "Joined",
    
    // Common
    "common.loading": "Loading...",
    "common.back": "Back",
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.submit": "Submit",
    "common.edit": "Edit",
    "common.delete": "Delete",
    "common.search": "Search",
    "common.filter": "Filter",
    "common.sort": "Sort",
    
    // Profile
    "profile.myProfile": "My Profile",
    "profile.level": "Level",
    "profile.followers": "Followers",
    "profile.following": "Following",
    "profile.submissions": "Submissions",
    "profile.achievements": "Achievements",
    "profile.editProfile": "Edit Profile",
    "profile.settings": "Settings",
    "profile.follow": "Follow",
    "profile.unfollow": "Unfollow",
    "profile.stats": "Stats",
    "profile.badges": "Badges",
    "profile.saveChanges": "Save Changes",
    "profile.displayName": "Display Name",
    "profile.bio": "Bio",
    "profile.changeAvatar": "Change Avatar",
    "profile.subscribe": "Subscribe",
    "profile.manageSubscription": "Manage Subscription",
    "profile.creatorPassActive": "Creator Pass Active",
    "profile.renewsOn": "Renews on",
    "profile.noBadges": "No badges earned yet",
    "profile.earnBadges": "Complete challenges to earn badges!",
    "profile.noSubmissions": "No submissions yet",
    "profile.startCreating": "Start creating to see your submissions here!",
    "profile.uploading": "Uploading...",
    "profile.saving": "Saving...",
    "profile.avatarTooLarge": "Avatar must be less than 5MB",
    "profile.profileUpdated": "Profile updated successfully!",
    "profile.updateFailed": "Failed to update profile",
    "profile.subscribeDesc": "Subscribe for $5/month for exclusive perks",
    "profile.manageDesc": "Manage your subscription settings",
    "profile.managing": "Loading...",
    
    // Leaderboard
    "leaderboard.title": "Leaderboard",
    "leaderboard.subtitle": "Top creators competing globally",
    "leaderboard.topCreators": "Top Creators",
    "leaderboard.rank": "Rank",
    "leaderboard.creator": "Creator",
    "leaderboard.thisWeek": "This Week",
    "leaderboard.allTime": "All Time",
    "leaderboard.daily": "Daily",
    "leaderboard.weekly": "Weekly",
    "leaderboard.comingSoon": "Coming Soon",
    "leaderboard.dailyComingSoon": "Daily leaderboards will be available soon!",
    "leaderboard.weeklyComingSoon": "Weekly leaderboards will be available soon!",
    "leaderboard.noRankings": "No rankings yet",
    "leaderboard.beFirstToEarn": "Be the first to earn points!",
    "leaderboard.pts": "pts",
    "leaderboard.points": "Points",
    
    // Feed
    "feed.title": "Community Feed",
    "feed.subtitle": "Explore the creator community",
    "feed.recent": "Recent",
    "feed.popular": "Popular",
    "feed.following": "Following",
    "feed.allSubmissions": "All Submissions",
    "feed.noSubmissions": "No submissions yet",
    "feed.beFirstToSubmit": "Be the first to submit to a challenge!",
    "feed.followCreatorsToSee": "Follow creators to see their submissions here!",
    "feed.signInToFollow": "Sign in to follow creators!",
    
    // Wallet
    "wallet.title": "Wallet",
    "wallet.subtitle": "Manage your balance and subscriptions",
    "wallet.balance": "Balance",
    "wallet.currentBalance": "Your current wallet balance",
    "wallet.creatorPass": "Creator Pass",
    "wallet.premiumSubscription": "Premium subscription for extra perks",
    "wallet.subscriptionDesc": "Subscribe for $5/month to get extra rewards, exclusive stats, and premium features",
    "wallet.subscribeNow": "Subscribe Now",
    "wallet.active": "Active",
    "wallet.transactions": "Transaction History",
    "wallet.recentActivity": "Your recent wallet activity",
    "wallet.history": "History",
    "wallet.topUp": "Top Up",
    "wallet.withdraw": "Withdraw",
    "wallet.noTransactions": "No transactions yet",
    "wallet.transactionType": "Type",
    "wallet.amount": "Amount",
    "wallet.date": "Date",
    
    // Challenge Detail
    "challenge.back": "Back",
    "challenge.joinChallenge": "Join Challenge",
    "challenge.submit": "Submit Entry",
    "challenge.uploadPhoto": "Upload Photo/Video",
    "challenge.caption": "Caption (Optional)",
    "challenge.yourSubmission": "Your Submission",
    "challenge.signInToParticipate": "Sign in to participate",
    "challenge.submitting": "Submitting...",
    "challenge.submitted": "Submitted",
    "challenge.editImage": "Edit Image",
    "challenge.boost": "Boost",
    "challenge.reEdit": "Re-Edit",
    "challenge.selectFile": "Select Photo/Video",
    "challenge.signInRequired": "Sign in to participate in challenges",
    "challenge.fillRequired": "Please upload a photo/video",
    "challenge.submittedSuccess": "Submission successful! +{points} points",
    "challenge.submissionFailed": "Failed to submit",
    "challenge.imageEdited": "Image edited successfully!",
    "challenge.pts": "pts",
    
    // Admin Panel
    "admin.panel": "Admin Panel",
    "admin.dashboard": "Dashboard",
    "admin.users": "Users",
    "admin.submissions": "Submissions",
    "admin.challenges": "Challenges",
    "admin.createChallenge": "Create Challenge",
    "admin.rewards": "Rewards",
    "admin.analytics": "Analytics",
    "admin.payments": "Payments",
    "admin.activityLogs": "Activity Logs",
    "admin.totalUsers": "Total Users",
    "admin.totalChallenges": "Total Challenges",
    "admin.totalSubmissions": "Total Submissions",
    "admin.pendingSubmissions": "Pending Submissions",
    "admin.challengeModeration": "Challenge Moderation",
    "admin.deleteSelected": "Delete Selected",
    "admin.selectAll": "Select All",
    "admin.challengeTitle": "Challenge Title",
    "admin.creator": "Creator",
    "admin.type": "Type",
    "admin.status": "Status",
    "admin.actions": "Actions",
    "admin.noChallenges": "No challenges found",
    "admin.challengeDeleted": "Challenge(s) deleted successfully",
    "admin.deleteFailed": "Failed to delete challenge",
    "admin.challengeDetails": "Challenge Details",
    "admin.challengeTitlePlaceholder": "Enter a catchy challenge title...",
    "admin.challengeDescription": "Description",
    "admin.challengeDescriptionPlaceholder": "Describe what participants need to do...",
    "admin.prize": "Prize",
    "admin.points": "Points",
    "admin.difficulty": "Difficulty",
    "admin.challengeType": "Challenge Type",
    "admin.daily": "Daily",
    "admin.weekly": "Weekly",
    "admin.duration": "Duration",
    "admin.durationDaysHint": "Number of days this challenge will last",
    "admin.durationWeeksHint": "Number of weeks this challenge will last",
    "admin.challengeImage": "Challenge Image (Optional)",
    "admin.creating": "Creating...",
    "admin.createChallengeButton": "Create Challenge",
    "admin.challengeCreated": "Challenge created successfully!",
    "admin.challengeCreateFailed": "Failed to create challenge",
    "admin.submissionModeration": "Submission Moderation",
    "admin.approve": "Approve",
    "admin.reject": "Reject",
    "admin.flag": "Flag",
    "admin.approveSelected": "Approve Selected",
    "admin.rejectSelected": "Reject Selected",
    "admin.username": "Username",
    "admin.challenge": "Challenge",
    "admin.submittedAt": "Submitted",
    "admin.noSubmissions": "No submissions found",
    "admin.approved": "Submission(s) approved",
    "admin.rejected": "Submission(s) rejected",
    "admin.moderationFailed": "Moderation failed",
    "admin.userManagement": "User Management",
    "admin.email": "Email",
    "admin.role": "Role",
    "admin.joinedDate": "Joined",
    "admin.assignRole": "Assign Role",
    "admin.removeRole": "Remove Role",
    "admin.noUsers": "No users found",
    "admin.roleAssigned": "Role assigned successfully",
    "admin.roleRemoved": "Role removed successfully",
    "admin.roleFailed": "Role operation failed",
    
    // Submission Card
    "submission.likedBy": "Liked by",
    "submission.people": "people",
    "submission.comment": "Comment",
    "submission.comments": "Comments",
    "submission.addComment": "Add a comment...",
    "submission.postComment": "Post",
    "submission.commentAdded": "Comment added!",
    "submission.commentFailed": "Failed to add comment",
    "submission.signInToVote": "Sign in to vote on submissions",
    "submission.voteFailed": "Failed to vote",
    "submission.boost": "Boost",
    "submission.reEdit": "Re-Edit",
    "submission.viewProfile": "View Profile",
    "submission.boosted": "Boosted",
    
    
    // Common - Extended
    "common.error": "Error",
    "common.success": "Success",
    "common.confirm": "Confirm",
    "common.close": "Close",
    "common.viewMore": "View More",
    "common.showLess": "Show Less",
    "common.signIn": "Sign In",
    "common.signUp": "Sign Up",
    "common.signOut": "Sign Out",
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const t = (key: string): string => {
    return translations[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
