import { createContext, useContext, useState, ReactNode, useEffect } from "react";

export type Language = "en" | "es" | "fr" | "de" | "pt" | "it" | "ja" | "ko" | "zh" | "ar" | "he";

const RTL_LANGUAGES: Language[] = ["ar", "he"];

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    "nav.home": "Home",
    "nav.challenges": "Challenges",
    "nav.feed": "Feed",
    "nav.leaderboard": "Leaderboard",
    "nav.profile": "Profile",
    "nav.wallet": "Wallet",
    "nav.referrals": "Referrals",
    "nav.admin": "Admin Panel",
    "nav.signOut": "Sign Out",
    "nav.signIn": "Sign In",
    "nav.getStarted": "Get Started",
    
    // Hero Section
    "hero.badge": "Join 100k+ Creators Worldwide",
    "hero.title1": "Create.",
    "hero.title2": "Compete.",
    "hero.title3": "Win Big.",
    "hero.description": "Join daily creative challenges, earn points and badges, compete with creators worldwide, and win real cash prizes. Your creativity has never been this rewarding!",
    "hero.cta": "Start Creating Now",
    "hero.howItWorks": "See How It Works",
    "hero.prizesWon": "Prizes Won",
    "hero.activeUsers": "Active Users",
    "hero.challenges": "Challenges",
    
    // Stats
    "stats.totalPrizes": "Total Prizes",
    "stats.awardedToCreators": "Awarded to creators",
    "stats.activeCreators": "Active Creators",
    "stats.creatingDaily": "Creating daily",
    "stats.dailyChallenges": "Daily Challenges",
    "stats.newEveryDay": "New every day",
    "stats.avgEarnings": "Avg Earnings",
    "stats.perMonth": "Per month",
    
    // Challenges
    "challenges.featured": "Featured Challenges",
    "challenges.trending": "Join these trending challenges and start earning today",
    "challenges.joinChallenge": "Join Challenge",
    "challenges.participants": "Participants",
    "challenges.timeLeft": "Time Left",
    "challenges.prize": "Prize",
    "challenges.points": "Points",
    "challenges.difficulty": "Difficulty",
    "challenges.easy": "Easy",
    "challenges.medium": "Medium",
    "challenges.hard": "Hard",
    
    // CTA
    "cta.title": "Ready to Turn Your Creativity Into Cash?",
    "cta.description": "Join thousands of creators earning money doing what they love. Sign up now and get 100 bonus points!",
    "cta.button": "Join Questify Free",
    
    // Auth
    "auth.login": "Login",
    "auth.signup": "Sign Up",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.username": "Username",
    "auth.displayName": "Display Name (Optional)",
    "auth.signIn": "Sign In",
    "auth.signInWith": "Or continue with",
    "auth.createAccount": "Create Account",
    "auth.signingIn": "Signing in...",
    "auth.creatingAccount": "Creating account...",
    
    // Referrals
    "referrals.title": "Referral Program",
    "referrals.description": "Invite friends and earn rewards together! Get 50 points for each friend who joins, and they get 25 points.",
    "referrals.totalReferrals": "Total Referrals",
    "referrals.totalEarnings": "Total Earnings",
    "referrals.rewardPerReferral": "Reward Per Referral",
    "referrals.yourCode": "Your Referral Code",
    "referrals.shareCode": "Share this code with friends to earn rewards",
    "referrals.copyLink": "Copy Link",
    "referrals.share": "Share",
    "referrals.shareOnSocial": "Share on social media",
    "referrals.howItWorks": "How it works:",
    "referrals.step1": "Share your referral code or link with friends",
    "referrals.step2": "They sign up using your code and get 25 bonus points",
    "referrals.step3": "You receive 50 points for each successful referral",
    "referrals.history": "Referral History",
    "referrals.noReferrals": "No referrals yet",
    "referrals.startSharing": "Share your referral code to start earning rewards!",
    "referrals.joined": "Joined",
    
    // Common
    "common.loading": "Loading...",
    "common.back": "Back",
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.submit": "Submit",
    "common.edit": "Edit",
    "common.delete": "Delete",
    "common.search": "Search",
    "common.filter": "Filter",
    "common.sort": "Sort",
    
    // Profile
    "profile.myProfile": "My Profile",
    "profile.level": "Level",
    "profile.followers": "Followers",
    "profile.following": "Following",
    "profile.submissions": "Submissions",
    "profile.achievements": "Achievements",
    "profile.editProfile": "Edit Profile",
    "profile.settings": "Settings",
    "profile.follow": "Follow",
    "profile.unfollow": "Unfollow",
    "profile.stats": "Stats",
    "profile.badges": "Badges",
    "profile.saveChanges": "Save Changes",
    "profile.displayName": "Display Name",
    "profile.bio": "Bio",
    "profile.changeAvatar": "Change Avatar",
    "profile.subscribe": "Subscribe",
    "profile.manageSubscription": "Manage Subscription",
    "profile.creatorPassActive": "Creator Pass Active",
    "profile.renewsOn": "Renews on",
    "profile.noBadges": "No badges earned yet",
    "profile.earnBadges": "Complete challenges to earn badges!",
    "profile.noSubmissions": "No submissions yet",
    "profile.startCreating": "Start creating to see your submissions here!",
    "profile.uploading": "Uploading...",
    "profile.saving": "Saving...",
    "profile.avatarTooLarge": "Avatar must be less than 5MB",
    "profile.profileUpdated": "Profile updated successfully!",
    "profile.updateFailed": "Failed to update profile",
    "profile.subscribeDesc": "Subscribe for $5/month for exclusive perks",
    "profile.manageDesc": "Manage your subscription settings",
    "profile.managing": "Loading...",
    
    // Leaderboard
    "leaderboard.title": "Leaderboard",
    "leaderboard.subtitle": "Top creators competing globally",
    "leaderboard.topCreators": "Top Creators",
    "leaderboard.rank": "Rank",
    "leaderboard.creator": "Creator",
    "leaderboard.thisWeek": "This Week",
    "leaderboard.allTime": "All Time",
    "leaderboard.daily": "Daily",
    "leaderboard.weekly": "Weekly",
    "leaderboard.comingSoon": "Coming Soon",
    "leaderboard.dailyComingSoon": "Daily leaderboards will be available soon!",
    "leaderboard.weeklyComingSoon": "Weekly leaderboards will be available soon!",
    "leaderboard.noRankings": "No rankings yet",
    "leaderboard.beFirstToEarn": "Be the first to earn points!",
    "leaderboard.pts": "pts",
    "leaderboard.points": "Points",
    
    // Feed
    "feed.title": "Community Feed",
    "feed.subtitle": "Explore the creator community",
    "feed.recent": "Recent",
    "feed.popular": "Popular",
    "feed.following": "Following",
    "feed.allSubmissions": "All Submissions",
    "feed.noSubmissions": "No submissions yet",
    "feed.beFirstToSubmit": "Be the first to submit to a challenge!",
    "feed.followCreatorsToSee": "Follow creators to see their submissions here!",
    "feed.signInToFollow": "Sign in to follow creators!",
    
    // Wallet
    "wallet.title": "Wallet",
    "wallet.subtitle": "Manage your balance and subscriptions",
    "wallet.balance": "Balance",
    "wallet.currentBalance": "Your current wallet balance",
    "wallet.creatorPass": "Creator Pass",
    "wallet.premiumSubscription": "Premium subscription for extra perks",
    "wallet.subscriptionDesc": "Subscribe for $5/month to get extra rewards, exclusive stats, and premium features",
    "wallet.subscribeNow": "Subscribe Now",
    "wallet.active": "Active",
    "wallet.transactions": "Transaction History",
    "wallet.recentActivity": "Your recent wallet activity",
    "wallet.history": "History",
    "wallet.topUp": "Top Up",
    "wallet.withdraw": "Withdraw",
    "wallet.noTransactions": "No transactions yet",
    "wallet.transactionType": "Type",
    "wallet.amount": "Amount",
    "wallet.date": "Date",
    
    // Challenge Detail
    "challenge.back": "Back",
    "challenge.joinChallenge": "Join Challenge",
    "challenge.submit": "Submit Entry",
    "challenge.uploadPhoto": "Upload Photo/Video",
    "challenge.caption": "Caption (Optional)",
    "challenge.yourSubmission": "Your Submission",
    "challenge.signInToParticipate": "Sign in to participate",
    "challenge.submitting": "Submitting...",
    "challenge.submitted": "Submitted",
    "challenge.editImage": "Edit Image",
    "challenge.boost": "Boost",
    "challenge.reEdit": "Re-Edit",
    "challenge.selectFile": "Select Photo/Video",
    "challenge.signInRequired": "Sign in to participate in challenges",
    "challenge.fillRequired": "Please upload a photo/video",
    "challenge.submittedSuccess": "Submission successful! +{points} points",
    "challenge.submissionFailed": "Failed to submit",
    "challenge.imageEdited": "Image edited successfully!",
    "challenge.pts": "pts",
    
    // Admin Panel
    "admin.panel": "Admin Panel",
    "admin.dashboard": "Dashboard",
    "admin.users": "Users",
    "admin.submissions": "Submissions",
    "admin.challenges": "Challenges",
    "admin.createChallenge": "Create Challenge",
    "admin.analytics": "Analytics",
    "admin.payments": "Payments",
    "admin.activityLogs": "Activity Logs",
    "admin.totalUsers": "Total Users",
    "admin.totalChallenges": "Total Challenges",
    "admin.totalSubmissions": "Total Submissions",
    "admin.pendingSubmissions": "Pending Submissions",
    "admin.challengeModeration": "Challenge Moderation",
    "admin.deleteSelected": "Delete Selected",
    "admin.selectAll": "Select All",
    "admin.challengeTitle": "Challenge Title",
    "admin.creator": "Creator",
    "admin.type": "Type",
    "admin.status": "Status",
    "admin.actions": "Actions",
    "admin.noChallenges": "No challenges found",
    "admin.challengeDeleted": "Challenge(s) deleted successfully",
    "admin.deleteFailed": "Failed to delete challenge",
    "admin.challengeDetails": "Challenge Details",
    "admin.challengeTitlePlaceholder": "Enter a catchy challenge title...",
    "admin.challengeDescription": "Description",
    "admin.challengeDescriptionPlaceholder": "Describe what participants need to do...",
    "admin.prize": "Prize",
    "admin.points": "Points",
    "admin.difficulty": "Difficulty",
    "admin.challengeType": "Challenge Type",
    "admin.daily": "Daily",
    "admin.weekly": "Weekly",
    "admin.duration": "Duration",
    "admin.durationDaysHint": "Number of days this challenge will last",
    "admin.durationWeeksHint": "Number of weeks this challenge will last",
    "admin.challengeImage": "Challenge Image (Optional)",
    "admin.creating": "Creating...",
    "admin.createChallengeButton": "Create Challenge",
    "admin.challengeCreated": "Challenge created successfully!",
    "admin.challengeCreateFailed": "Failed to create challenge",
    "admin.submissionModeration": "Submission Moderation",
    "admin.approve": "Approve",
    "admin.reject": "Reject",
    "admin.flag": "Flag",
    "admin.approveSelected": "Approve Selected",
    "admin.rejectSelected": "Reject Selected",
    "admin.username": "Username",
    "admin.challenge": "Challenge",
    "admin.submittedAt": "Submitted",
    "admin.noSubmissions": "No submissions found",
    "admin.approved": "Submission(s) approved",
    "admin.rejected": "Submission(s) rejected",
    "admin.moderationFailed": "Moderation failed",
    "admin.userManagement": "User Management",
    "admin.email": "Email",
    "admin.role": "Role",
    "admin.joinedDate": "Joined",
    "admin.assignRole": "Assign Role",
    "admin.removeRole": "Remove Role",
    "admin.noUsers": "No users found",
    "admin.roleAssigned": "Role assigned successfully",
    "admin.roleRemoved": "Role removed successfully",
    "admin.roleFailed": "Role operation failed",
    
    // Submission Card
    "submission.likedBy": "Liked by",
    "submission.people": "people",
    "submission.comment": "Comment",
    "submission.comments": "Comments",
    "submission.addComment": "Add a comment...",
    "submission.postComment": "Post",
    "submission.commentAdded": "Comment added!",
    "submission.commentFailed": "Failed to add comment",
    "submission.signInToVote": "Sign in to vote on submissions",
    "submission.voteFailed": "Failed to vote",
    "submission.boost": "Boost",
    "submission.reEdit": "Re-Edit",
    "submission.viewProfile": "View Profile",
    "submission.boosted": "Boosted",
    
    
    // Common - Extended
    "common.error": "Error",
    "common.success": "Success",
    "common.confirm": "Confirm",
    "common.close": "Close",
    "common.viewMore": "View More",
    "common.showLess": "Show Less",
    "common.signIn": "Sign In",
    "common.signUp": "Sign Up",
    "common.signOut": "Sign Out",
  },
  es: {
    // Navigation
    "nav.home": "Inicio",
    "nav.challenges": "Desafíos",
    "nav.feed": "Feed",
    "nav.leaderboard": "Clasificación",
    "nav.profile": "Perfil",
    "nav.wallet": "Cartera",
    "nav.referrals": "Referencias",
    "nav.admin": "Panel Admin",
    "nav.signOut": "Cerrar Sesión",
    "nav.signIn": "Iniciar Sesión",
    "nav.getStarted": "Comenzar",
    
    // Hero
    "hero.badge": "Únete a 100k+ Creadores en Todo el Mundo",
    "hero.title1": "Crea.",
    "hero.title2": "Compite.",
    "hero.title3": "Gana en Grande.",
    "hero.description": "Únete a desafíos creativos diarios, gana puntos y medallas, compite con creadores de todo el mundo y gana premios en efectivo reales. ¡Tu creatividad nunca ha sido tan gratificante!",
    "hero.cta": "Comienza a Crear Ahora",
    "hero.howItWorks": "Cómo Funciona",
    "hero.prizesWon": "Premios Ganados",
    "hero.activeUsers": "Usuarios Activos",
    "hero.challenges": "Desafíos",
    
    // Stats
    "stats.totalPrizes": "Premios Totales",
    "stats.awardedToCreators": "Otorgados a creadores",
    "stats.activeCreators": "Creadores Activos",
    "stats.creatingDaily": "Creando diariamente",
    "stats.dailyChallenges": "Desafíos Diarios",
    "stats.newEveryDay": "Nuevos cada día",
    "stats.avgEarnings": "Ganancias Promedio",
    "stats.perMonth": "Por mes",
    
    // Challenges
    "challenges.featured": "Desafíos Destacados",
    "challenges.trending": "Únete a estos desafíos populares y comienza a ganar hoy",
    "challenges.joinChallenge": "Unirse al Desafío",
    "challenges.participants": "Participantes",
    "challenges.timeLeft": "Tiempo Restante",
    "challenges.prize": "Premio",
    "challenges.points": "Puntos",
    "challenges.difficulty": "Dificultad",
    "challenges.easy": "Fácil",
    "challenges.medium": "Medio",
    "challenges.hard": "Difícil",
    
    // CTA
    "cta.title": "¿Listo para Convertir tu Creatividad en Dinero?",
    "cta.description": "Únete a miles de creadores ganando dinero haciendo lo que aman. ¡Regístrate ahora y obtén 100 puntos de bonificación!",
    "cta.button": "Únete a Questify Gratis",
    
    // Auth
    "auth.login": "Iniciar Sesión",
    "auth.signup": "Registrarse",
    "auth.email": "Correo Electrónico",
    "auth.password": "Contraseña",
    "auth.username": "Nombre de Usuario",
    "auth.displayName": "Nombre para Mostrar (Opcional)",
    "auth.signIn": "Iniciar Sesión",
    "auth.signInWith": "O continuar con",
    "auth.createAccount": "Crear Cuenta",
    "auth.signingIn": "Iniciando sesión...",
    "auth.creatingAccount": "Creando cuenta...",
    
    // Referrals
    "referrals.title": "Programa de Referencias",
    "referrals.description": "¡Invita amigos y gana recompensas juntos! Obtén 50 puntos por cada amigo que se una, y ellos reciben 25 puntos.",
    "referrals.totalReferrals": "Referencias Totales",
    "referrals.totalEarnings": "Ganancias Totales",
    "referrals.rewardPerReferral": "Recompensa por Referencia",
    "referrals.yourCode": "Tu Código de Referencia",
    "referrals.shareCode": "Comparte este código con amigos para ganar recompensas",
    "referrals.copyLink": "Copiar Enlace",
    "referrals.share": "Compartir",
    "referrals.shareOnSocial": "Compartir en redes sociales",
    "referrals.howItWorks": "Cómo funciona:",
    "referrals.step1": "Comparte tu código de referencia o enlace con amigos",
    "referrals.step2": "Se registran usando tu código y obtienen 25 puntos de bonificación",
    "referrals.step3": "Recibes 50 puntos por cada referencia exitosa",
    "referrals.history": "Historial de Referencias",
    "referrals.noReferrals": "Aún no hay referencias",
    "referrals.startSharing": "¡Comparte tu código de referencia para comenzar a ganar recompensas!",
    "referrals.joined": "Se unió",
    
    // Common
    "common.loading": "Cargando...",
    "common.back": "Atrás",
    "common.save": "Guardar",
    "common.cancel": "Cancelar",
    "common.submit": "Enviar",
    "common.edit": "Editar",
    "common.delete": "Eliminar",
    "common.search": "Buscar",
    "common.filter": "Filtrar",
    "common.sort": "Ordenar",
    
    // Profile
    "profile.myProfile": "Mi Perfil",
    "profile.level": "Nivel",
    "profile.followers": "Seguidores",
    "profile.following": "Siguiendo",
    "profile.submissions": "Envíos",
    "profile.achievements": "Logros",
    "profile.editProfile": "Editar Perfil",
    "profile.settings": "Configuración",
    
    // Leaderboard
    "leaderboard.title": "Clasificación",
    "leaderboard.topCreators": "Mejores Creadores",
    "leaderboard.rank": "Rango",
    "leaderboard.creator": "Creador",
    "leaderboard.thisWeek": "Esta Semana",
    "leaderboard.allTime": "Todos los Tiempos",
    
    // Feed
    "feed.title": "Feed",
    "feed.recent": "Recientes",
    "feed.popular": "Populares",
    "feed.following": "Siguiendo",
    "feed.noSubmissions": "No hay envíos todavía",
    
    // Wallet
    "wallet.title": "Cartera",
    "wallet.balance": "Saldo",
    "wallet.transactions": "Transacciones",
    "wallet.history": "Historial",
    "wallet.topUp": "Recargar",
    "wallet.withdraw": "Retirar",
    
    // Challenge Detail
    "challenge.back": "Atrás",
    "challenge.joinChallenge": "Unirse al Desafío",
    "challenge.submit": "Enviar Participación",
    "challenge.uploadPhoto": "Subir Foto/Video",
    "challenge.caption": "Leyenda (Opcional)",
    "challenge.yourSubmission": "Tu Envío",
    "challenge.signInToParticipate": "Inicia sesión para participar",
    "challenge.submitting": "Enviando...",
    "challenge.submitted": "Enviado",
    "challenge.editImage": "Editar Imagen",
    "challenge.boost": "Impulsar",
    "challenge.reEdit": "Re-editar",
    "challenge.selectFile": "Seleccionar Foto/Video",
    "challenge.signInRequired": "Inicia sesión para participar en desafíos",
    "challenge.fillRequired": "Por favor sube una foto/video",
    "challenge.submittedSuccess": "¡Envío exitoso! +{points} puntos",
    "challenge.submissionFailed": "Error al enviar",
    "challenge.imageEdited": "¡Imagen editada exitosamente!",
    "challenge.pts": "pts",
    
    // Admin Panel
    "admin.panel": "Panel de Administración",
    "admin.dashboard": "Panel",
    "admin.users": "Usuarios",
    "admin.submissions": "Envíos",
    "admin.challenges": "Desafíos",
    "admin.createChallenge": "Crear Desafío",
    "admin.analytics": "Analíticas",
    "admin.payments": "Pagos",
    "admin.activityLogs": "Registros de Actividad",
    "admin.totalUsers": "Usuarios Totales",
    "admin.totalChallenges": "Desafíos Totales",
    "admin.totalSubmissions": "Envíos Totales",
    "admin.pendingSubmissions": "Envíos Pendientes",
    "admin.challengeModeration": "Moderación de Desafíos",
    "admin.deleteSelected": "Eliminar Seleccionados",
    "admin.selectAll": "Seleccionar Todos",
    "admin.challengeTitle": "Título del Desafío",
    "admin.creator": "Creador",
    "admin.type": "Tipo",
    "admin.status": "Estado",
    "admin.actions": "Acciones",
    "admin.noChallenges": "No se encontraron desafíos",
    "admin.challengeDeleted": "Desafío(s) eliminado(s) exitosamente",
    "admin.deleteFailed": "Error al eliminar desafío",
    "admin.challengeDetails": "Detalles del Desafío",
    "admin.challengeTitlePlaceholder": "Ingresa un título atractivo...",
    "admin.challengeDescription": "Descripción",
    "admin.challengeDescriptionPlaceholder": "Describe lo que los participantes necesitan hacer...",
    "admin.prize": "Premio",
    "admin.points": "Puntos",
    "admin.difficulty": "Dificultad",
    "admin.challengeType": "Tipo de Desafío",
    "admin.daily": "Diario",
    "admin.weekly": "Semanal",
    "admin.duration": "Duración",
    "admin.durationDaysHint": "Número de días que durará este desafío",
    "admin.durationWeeksHint": "Número de semanas que durará este desafío",
    "admin.challengeImage": "Imagen del Desafío (Opcional)",
    "admin.creating": "Creando...",
    "admin.createChallengeButton": "Crear Desafío",
    "admin.challengeCreated": "¡Desafío creado exitosamente!",
    "admin.challengeCreateFailed": "Error al crear desafío",
    "admin.submissionModeration": "Moderación de Envíos",
    "admin.approve": "Aprobar",
    "admin.reject": "Rechazar",
    "admin.flag": "Marcar",
    "admin.approveSelected": "Aprobar Seleccionados",
    "admin.rejectSelected": "Rechazar Seleccionados",
    "admin.username": "Nombre de Usuario",
    "admin.challenge": "Desafío",
    "admin.submittedAt": "Enviado",
    "admin.noSubmissions": "No se encontraron envíos",
    "admin.approved": "Envío(s) aprobado(s)",
    "admin.rejected": "Envío(s) rechazado(s)",
    "admin.moderationFailed": "Moderación fallida",
    "admin.userManagement": "Gestión de Usuarios",
    "admin.email": "Correo Electrónico",
    "admin.role": "Rol",
    "admin.joinedDate": "Se unió",
    "admin.assignRole": "Asignar Rol",
    "admin.removeRole": "Eliminar Rol",
    "admin.noUsers": "No se encontraron usuarios",
    "admin.roleAssigned": "Rol asignado exitosamente",
    "admin.roleRemoved": "Rol eliminado exitosamente",
    "admin.roleFailed": "Operación de rol fallida",
    
    // Submission Card
    "submission.likedBy": "Le gusta a",
    "submission.people": "personas",
    "submission.comment": "Comentario",
    "submission.comments": "Comentarios",
    "submission.addComment": "Añadir un comentario...",
    "submission.postComment": "Publicar",
    "submission.commentAdded": "¡Comentario añadido!",
    "submission.commentFailed": "Error al añadir comentario",
    "submission.signInToVote": "Inicia sesión para votar envíos",
    "submission.voteFailed": "Error al votar",
    "submission.boost": "Impulsar",
    "submission.reEdit": "Re-editar",
    "submission.viewProfile": "Ver Perfil",
    "submission.boosted": "Impulsado",
    
    // Profile - Extended
    "profile.follow": "Seguir",
    "profile.unfollow": "Dejar de seguir",
    "profile.stats": "Estadísticas",
    "profile.badges": "Insignias",
    "profile.saveChanges": "Guardar Cambios",
    "profile.displayName": "Nombre para Mostrar",
    "profile.bio": "Biografía",
    "profile.changeAvatar": "Cambiar Avatar",
    "profile.subscribe": "Suscribirse",
    "profile.manageSubscription": "Gestionar Suscripción",
    "profile.creatorPassActive": "Pase de Creador Activo",
    "profile.renewsOn": "Se renueva el",
    "profile.noBadges": "Aún no hay insignias",
    "profile.earnBadges": "¡Completa desafíos para ganar insignias!",
    "profile.noSubmissions": "Aún no hay envíos",
    "profile.startCreating": "¡Comienza a crear para ver tus envíos aquí!",
    "profile.uploading": "Subiendo...",
    "profile.saving": "Guardando...",
    "profile.avatarTooLarge": "El avatar debe ser menor de 5MB",
    "profile.profileUpdated": "¡Perfil actualizado exitosamente!",
    "profile.updateFailed": "Error al actualizar perfil",
    "profile.subscribeDesc": "Suscríbete por $5/mes para beneficios exclusivos",
    "profile.manageDesc": "Gestiona tu configuración de suscripción",
    "profile.managing": "Cargando...",
    
    // Leaderboard - Extended
    "leaderboard.subtitle": "Mejores creadores compitiendo globalmente",
    "leaderboard.daily": "Diario",
    "leaderboard.weekly": "Semanal",
    "leaderboard.comingSoon": "Próximamente",
    "leaderboard.dailyComingSoon": "¡Las clasificaciones diarias estarán disponibles pronto!",
    "leaderboard.weeklyComingSoon": "¡Las clasificaciones semanales estarán disponibles pronto!",
    "leaderboard.noRankings": "Aún no hay clasificaciones",
    "leaderboard.beFirstToEarn": "¡Sé el primero en ganar puntos!",
    "leaderboard.pts": "pts",
    "leaderboard.points": "Puntos",
    
    // Feed - Extended
    "feed.subtitle": "Explora la comunidad de creadores",
    "feed.allSubmissions": "Todos los Envíos",
    "feed.beFirstToSubmit": "¡Sé el primero en enviar a un desafío!",
    "feed.followCreatorsToSee": "¡Sigue creadores para ver sus envíos aquí!",
    "feed.signInToFollow": "¡Inicia sesión para seguir creadores!",
    
    // Wallet - Extended
    "wallet.subtitle": "Gestiona tu saldo y suscripciones",
    "wallet.currentBalance": "Tu saldo actual",
    "wallet.creatorPass": "Pase de Creador",
    "wallet.premiumSubscription": "Suscripción premium para beneficios adicionales",
    "wallet.subscriptionDesc": "Suscríbete por $5/mes para obtener recompensas extra, estadísticas exclusivas y funciones premium",
    "wallet.subscribeNow": "Suscribirse Ahora",
    "wallet.active": "Activo",
    "wallet.recentActivity": "Tu actividad reciente de cartera",
    "wallet.noTransactions": "Aún no hay transacciones",
    "wallet.transactionType": "Tipo",
    "wallet.amount": "Monto",
    "wallet.date": "Fecha",
    
    // Common - Extended
    "common.error": "Error",
    "common.success": "Éxito",
    "common.confirm": "Confirmar",
    "common.close": "Cerrar",
    "common.viewMore": "Ver Más",
    "common.showLess": "Mostrar Menos",
    "common.signIn": "Iniciar Sesión",
    "common.signUp": "Registrarse",
    "common.signOut": "Cerrar Sesión",
  },
  fr: {
    "nav.home": "Accueil",
    "nav.challenges": "Défis",
    "nav.feed": "Fil",
    "nav.leaderboard": "Classement",
    "nav.profile": "Profil",
    "nav.wallet": "Portefeuille",
    "nav.referrals": "Parrainages",
    "nav.admin": "Panel Admin",
    "nav.signOut": "Déconnexion",
    "nav.signIn": "Connexion",
    "nav.getStarted": "Commencer",
    
    "hero.badge": "Rejoignez 100k+ Créateurs dans le Monde",
    "hero.title1": "Créer.",
    "hero.title2": "Compétitionner.",
    "hero.title3": "Gagner Gros.",
    "hero.description": "Participez à des défis créatifs quotidiens, gagnez des points et des badges, affrontez des créateurs du monde entier et remportez de vrais prix en espèces. Votre créativité n'a jamais été aussi gratifiante !",
    "hero.cta": "Commencer à Créer",
    "hero.howItWorks": "Comment Ça Marche",
    "hero.prizesWon": "Prix Gagnés",
    "hero.activeUsers": "Utilisateurs Actifs",
    "hero.challenges": "Défis",
    
    "stats.totalPrizes": "Prix Totaux",
    "stats.awardedToCreators": "Attribués aux créateurs",
    "stats.activeCreators": "Créateurs Actifs",
    "stats.creatingDaily": "Créant quotidiennement",
    "stats.dailyChallenges": "Défis Quotidiens",
    "stats.newEveryDay": "Nouveaux chaque jour",
    "stats.avgEarnings": "Gains Moyens",
    "stats.perMonth": "Par mois",
    
    "challenges.featured": "Défis en Vedette",
    "challenges.trending": "Rejoignez ces défis tendance et commencez à gagner aujourd'hui",
    "challenges.joinChallenge": "Rejoindre le Défi",
    "challenges.participants": "Participants",
    "challenges.timeLeft": "Temps Restant",
    "challenges.prize": "Prix",
    "challenges.points": "Points",
    "challenges.difficulty": "Difficulté",
    "challenges.easy": "Facile",
    "challenges.medium": "Moyen",
    "challenges.hard": "Difficile",
    
    "cta.title": "Prêt à Transformer Votre Créativité en Argent ?",
    "cta.description": "Rejoignez des milliers de créateurs gagnant de l'argent en faisant ce qu'ils aiment. Inscrivez-vous maintenant et obtenez 100 points bonus !",
    "cta.button": "Rejoindre Questify Gratuitement",
    
    "auth.login": "Connexion",
    "auth.signup": "S'inscrire",
    "auth.email": "Email",
    "auth.password": "Mot de passe",
    "auth.username": "Nom d'utilisateur",
    "auth.displayName": "Nom d'affichage (Optionnel)",
    "auth.signIn": "Se Connecter",
    "auth.signInWith": "Ou continuer avec",
    "auth.createAccount": "Créer un Compte",
    "auth.signingIn": "Connexion...",
    "auth.creatingAccount": "Création du compte...",
    
    "referrals.title": "Programme de Parrainage",
    "referrals.description": "Invitez des amis et gagnez des récompenses ensemble ! Obtenez 50 points pour chaque ami qui rejoint, et ils reçoivent 25 points.",
    "referrals.totalReferrals": "Parrainages Totaux",
    "referrals.totalEarnings": "Gains Totaux",
    "referrals.rewardPerReferral": "Récompense par Parrainage",
    "referrals.yourCode": "Votre Code de Parrainage",
    "referrals.shareCode": "Partagez ce code avec vos amis pour gagner des récompenses",
    "referrals.copyLink": "Copier le Lien",
    "referrals.share": "Partager",
    "referrals.shareOnSocial": "Partager sur les réseaux sociaux",
    "referrals.howItWorks": "Comment ça marche :",
    "referrals.step1": "Partagez votre code de parrainage ou lien avec des amis",
    "referrals.step2": "Ils s'inscrivent en utilisant votre code et obtiennent 25 points bonus",
    "referrals.step3": "Vous recevez 50 points pour chaque parrainage réussi",
    "referrals.history": "Historique des Parrainages",
    "referrals.noReferrals": "Aucun parrainage encore",
    "referrals.startSharing": "Partagez votre code de parrainage pour commencer à gagner des récompenses !",
    "referrals.joined": "A rejoint",
    
    "common.loading": "Chargement...",
    "common.back": "Retour",
    "common.save": "Enregistrer",
    "common.cancel": "Annuler",
    "common.submit": "Soumettre",
    "common.edit": "Modifier",
    "common.delete": "Supprimer",
    "common.search": "Rechercher",
    "common.filter": "Filtrer",
    "common.sort": "Trier",
    
    // Profile
    "profile.myProfile": "Mon Profil",
    "profile.level": "Niveau",
    "profile.followers": "Abonnés",
    "profile.following": "Abonnements",
    "profile.submissions": "Soumissions",
    "profile.achievements": "Réalisations",
    "profile.editProfile": "Modifier le Profil",
    "profile.settings": "Paramètres",
    
    // Leaderboard
    "leaderboard.title": "Classement",
    "leaderboard.topCreators": "Meilleurs Créateurs",
    "leaderboard.rank": "Rang",
    "leaderboard.creator": "Créateur",
    "leaderboard.thisWeek": "Cette Semaine",
    "leaderboard.allTime": "Tous les Temps",
    
    // Feed
    "feed.title": "Fil",
    "feed.recent": "Récents",
    "feed.popular": "Populaires",
    "feed.following": "Abonnements",
    "feed.noSubmissions": "Pas encore de soumissions",
    
    // Wallet
    "wallet.title": "Portefeuille",
    "wallet.balance": "Solde",
    "wallet.transactions": "Transactions",
    "wallet.history": "Historique",
    "wallet.topUp": "Recharger",
    "wallet.withdraw": "Retirer",
    
    // Challenge Detail
    "challenge.submit": "Soumettre la Participation",
    "challenge.uploadPhoto": "Télécharger Photo/Vidéo",
    "challenge.caption": "Légende (Optionnel)",
    "challenge.yourSubmission": "Votre Soumission",
    "challenge.signInToParticipate": "Connectez-vous pour participer",
    "challenge.submitting": "Envoi...",
    "challenge.submitted": "Soumis",
    "challenge.editImage": "Modifier l'Image",
  },
  de: {
    "nav.home": "Startseite",
    "nav.challenges": "Herausforderungen",
    "nav.feed": "Feed",
    "nav.leaderboard": "Bestenliste",
    "nav.profile": "Profil",
    "nav.wallet": "Geldbörse",
    "nav.referrals": "Empfehlungen",
    "nav.admin": "Admin-Panel",
    "nav.signOut": "Abmelden",
    "nav.signIn": "Anmelden",
    "nav.getStarted": "Loslegen",
    
    "hero.badge": "Schließe dich 100k+ Kreativen weltweit an",
    "hero.title1": "Erstellen.",
    "hero.title2": "Konkurrieren.",
    "hero.title3": "Groß Gewinnen.",
    "hero.description": "Nimm an täglichen kreativen Herausforderungen teil, verdiene Punkte und Abzeichen, trete gegen Kreative weltweit an und gewinne echte Geldpreise. Deine Kreativität war noch nie so lohnend!",
    "hero.cta": "Jetzt Loslegen",
    "hero.howItWorks": "Wie es Funktioniert",
    "hero.prizesWon": "Gewonnene Preise",
    "hero.activeUsers": "Aktive Nutzer",
    "hero.challenges": "Herausforderungen",
    
    "stats.totalPrizes": "Gesamtpreise",
    "stats.awardedToCreators": "An Kreative vergeben",
    "stats.activeCreators": "Aktive Kreative",
    "stats.creatingDaily": "Täglich kreativ",
    "stats.dailyChallenges": "Tägliche Herausforderungen",
    "stats.newEveryDay": "Jeden Tag neu",
    "stats.avgEarnings": "Durchschnittl. Einnahmen",
    "stats.perMonth": "Pro Monat",
    
    "challenges.featured": "Empfohlene Herausforderungen",
    "challenges.trending": "Schließe dich diesen Trend-Herausforderungen an und beginne heute zu verdienen",
    "challenges.joinChallenge": "Herausforderung Beitreten",
    "challenges.participants": "Teilnehmer",
    "challenges.timeLeft": "Verbleibende Zeit",
    "challenges.prize": "Preis",
    "challenges.points": "Punkte",
    "challenges.difficulty": "Schwierigkeit",
    "challenges.easy": "Einfach",
    "challenges.medium": "Mittel",
    "challenges.hard": "Schwer",
    
    "cta.title": "Bereit, Deine Kreativität in Geld zu Verwandeln?",
    "cta.description": "Schließe dich Tausenden von Kreativen an, die Geld verdienen, indem sie das tun, was sie lieben. Melde dich jetzt an und erhalte 100 Bonuspunkte!",
    "cta.button": "Kostenlos bei Questify Mitmachen",
    
    "auth.login": "Anmelden",
    "auth.signup": "Registrieren",
    "auth.email": "E-Mail",
    "auth.password": "Passwort",
    "auth.username": "Benutzername",
    "auth.displayName": "Anzeigename (Optional)",
    "auth.signIn": "Einloggen",
    "auth.signInWith": "Oder fortfahren mit",
    "auth.createAccount": "Konto Erstellen",
    "auth.signingIn": "Anmeldung läuft...",
    "auth.creatingAccount": "Konto wird erstellt...",
    
    "referrals.title": "Empfehlungsprogramm",
    "referrals.description": "Lade Freunde ein und verdiene gemeinsam Belohnungen! Erhalte 50 Punkte für jeden Freund, der beitritt, und sie erhalten 25 Punkte.",
    "referrals.totalReferrals": "Gesamte Empfehlungen",
    "referrals.totalEarnings": "Gesamteinnahmen",
    "referrals.rewardPerReferral": "Belohnung pro Empfehlung",
    "referrals.yourCode": "Dein Empfehlungscode",
    "referrals.shareCode": "Teile diesen Code mit Freunden, um Belohnungen zu verdienen",
    "referrals.copyLink": "Link Kopieren",
    "referrals.share": "Teilen",
    "referrals.shareOnSocial": "In sozialen Medien teilen",
    "referrals.howItWorks": "So funktioniert's:",
    "referrals.step1": "Teile deinen Empfehlungscode oder Link mit Freunden",
    "referrals.step2": "Sie melden sich mit deinem Code an und erhalten 25 Bonuspunkte",
    "referrals.step3": "Du erhältst 50 Punkte für jede erfolgreiche Empfehlung",
    "referrals.history": "Empfehlungsverlauf",
    "referrals.noReferrals": "Noch keine Empfehlungen",
    "referrals.startSharing": "Teile deinen Empfehlungscode, um Belohnungen zu verdienen!",
    "referrals.joined": "Beigetreten",
    
    "common.loading": "Lädt...",
    "common.back": "Zurück",
    "common.save": "Speichern",
    "common.cancel": "Abbrechen",
    "common.submit": "Senden",
    "common.edit": "Bearbeiten",
    "common.delete": "Löschen",
    "common.search": "Suchen",
    "common.filter": "Filtern",
    "common.sort": "Sortieren",
    
    // Profile
    "profile.myProfile": "Mein Profil",
    "profile.level": "Level",
    "profile.followers": "Follower",
    "profile.following": "Folge ich",
    "profile.submissions": "Einreichungen",
    "profile.achievements": "Erfolge",
    "profile.editProfile": "Profil Bearbeiten",
    "profile.settings": "Einstellungen",
    
    // Leaderboard
    "leaderboard.title": "Bestenliste",
    "leaderboard.topCreators": "Top Kreative",
    "leaderboard.rank": "Rang",
    "leaderboard.creator": "Kreativer",
    "leaderboard.thisWeek": "Diese Woche",
    "leaderboard.allTime": "Alle Zeiten",
    
    // Feed
    "feed.title": "Feed",
    "feed.recent": "Neueste",
    "feed.popular": "Beliebt",
    "feed.following": "Folge ich",
    "feed.noSubmissions": "Noch keine Einreichungen",
    
    // Wallet
    "wallet.title": "Geldbörse",
    "wallet.balance": "Guthaben",
    "wallet.transactions": "Transaktionen",
    "wallet.history": "Verlauf",
    "wallet.topUp": "Aufladen",
    "wallet.withdraw": "Abheben",
    
    // Challenge Detail
    "challenge.submit": "Beitrag Einreichen",
    "challenge.uploadPhoto": "Foto/Video Hochladen",
    "challenge.caption": "Beschriftung (Optional)",
    "challenge.yourSubmission": "Deine Einreichung",
    "challenge.signInToParticipate": "Melde dich an, um teilzunehmen",
    "challenge.submitting": "Wird eingereicht...",
    "challenge.submitted": "Eingereicht",
    "challenge.editImage": "Bild Bearbeiten",
  },
  pt: {
    "nav.home": "Início",
    "nav.challenges": "Desafios",
    "nav.feed": "Feed",
    "nav.leaderboard": "Classificação",
    "nav.profile": "Perfil",
    "nav.wallet": "Carteira",
    "nav.referrals": "Indicações",
    "nav.admin": "Painel Admin",
    "nav.signOut": "Sair",
    "nav.signIn": "Entrar",
    "nav.getStarted": "Começar",
    
    "hero.badge": "Junte-se a 100k+ Criadores Mundialmente",
    "hero.title1": "Criar.",
    "hero.title2": "Competir.",
    "hero.title3": "Ganhar Grande.",
    "hero.description": "Participe de desafios criativos diários, ganhe pontos e distintivos, compita com criadores do mundo todo e ganhe prêmios em dinheiro real. Sua criatividade nunca foi tão recompensadora!",
    "hero.cta": "Comece a Criar Agora",
    "hero.howItWorks": "Como Funciona",
    "hero.prizesWon": "Prêmios Ganhos",
    "hero.activeUsers": "Usuários Ativos",
    "hero.challenges": "Desafios",
    
    "stats.totalPrizes": "Prêmios Totais",
    "stats.awardedToCreators": "Concedidos a criadores",
    "stats.activeCreators": "Criadores Ativos",
    "stats.creatingDaily": "Criando diariamente",
    "stats.dailyChallenges": "Desafios Diários",
    "stats.newEveryDay": "Novos todos os dias",
    "stats.avgEarnings": "Ganhos Médios",
    "stats.perMonth": "Por mês",
    
    "challenges.featured": "Desafios em Destaque",
    "challenges.trending": "Participe destes desafios em alta e comece a ganhar hoje",
    "challenges.joinChallenge": "Participar do Desafio",
    "challenges.participants": "Participantes",
    "challenges.timeLeft": "Tempo Restante",
    "challenges.prize": "Prêmio",
    "challenges.points": "Pontos",
    "challenges.difficulty": "Dificuldade",
    "challenges.easy": "Fácil",
    "challenges.medium": "Médio",
    "challenges.hard": "Difícil",
    
    "cta.title": "Pronto para Transformar Sua Criatividade em Dinheiro?",
    "cta.description": "Junte-se a milhares de criadores ganhando dinheiro fazendo o que amam. Cadastre-se agora e ganhe 100 pontos de bônus!",
    "cta.button": "Entrar no Questify Grátis",
    
    "auth.login": "Entrar",
    "auth.signup": "Cadastrar",
    "auth.email": "Email",
    "auth.password": "Senha",
    "auth.username": "Nome de Usuário",
    "auth.displayName": "Nome de Exibição (Opcional)",
    "auth.signIn": "Fazer Login",
    "auth.signInWith": "Ou continuar com",
    "auth.createAccount": "Criar Conta",
    "auth.signingIn": "Entrando...",
    "auth.creatingAccount": "Criando conta...",
    
    "referrals.title": "Programa de Indicações",
    "referrals.description": "Convide amigos e ganhe recompensas juntos! Ganhe 50 pontos para cada amigo que se juntar, e eles ganham 25 pontos.",
    "referrals.totalReferrals": "Indicações Totais",
    "referrals.totalEarnings": "Ganhos Totais",
    "referrals.rewardPerReferral": "Recompensa por Indicação",
    "referrals.yourCode": "Seu Código de Indicação",
    "referrals.shareCode": "Compartilhe este código com amigos para ganhar recompensas",
    "referrals.copyLink": "Copiar Link",
    "referrals.share": "Compartilhar",
    "referrals.shareOnSocial": "Compartilhar nas redes sociais",
    "referrals.howItWorks": "Como funciona:",
    "referrals.step1": "Compartilhe seu código de indicação ou link com amigos",
    "referrals.step2": "Eles se cadastram usando seu código e ganham 25 pontos de bônus",
    "referrals.step3": "Você recebe 50 pontos para cada indicação bem-sucedida",
    "referrals.history": "Histórico de Indicações",
    "referrals.noReferrals": "Nenhuma indicação ainda",
    "referrals.startSharing": "Compartilhe seu código de indicação para começar a ganhar recompensas!",
    "referrals.joined": "Entrou em",
    
    "common.loading": "Carregando...",
    "common.back": "Voltar",
    "common.save": "Salvar",
    "common.cancel": "Cancelar",
    "common.submit": "Enviar",
    "common.edit": "Editar",
    "common.delete": "Excluir",
    "common.search": "Pesquisar",
    "common.filter": "Filtrar",
    "common.sort": "Ordenar",
    
    // Profile
    "profile.myProfile": "Meu Perfil",
    "profile.level": "Nível",
    "profile.followers": "Seguidores",
    "profile.following": "Seguindo",
    "profile.submissions": "Envios",
    "profile.achievements": "Conquistas",
    "profile.editProfile": "Editar Perfil",
    "profile.settings": "Configurações",
    
    // Leaderboard
    "leaderboard.title": "Classificação",
    "leaderboard.topCreators": "Melhores Criadores",
    "leaderboard.rank": "Posição",
    "leaderboard.creator": "Criador",
    "leaderboard.thisWeek": "Esta Semana",
    "leaderboard.allTime": "Todos os Tempos",
    
    // Feed
    "feed.title": "Feed",
    "feed.recent": "Recentes",
    "feed.popular": "Populares",
    "feed.following": "Seguindo",
    "feed.noSubmissions": "Nenhum envio ainda",
    
    // Wallet
    "wallet.title": "Carteira",
    "wallet.balance": "Saldo",
    "wallet.transactions": "Transações",
    "wallet.history": "Histórico",
    "wallet.topUp": "Recarregar",
    "wallet.withdraw": "Sacar",
    
    // Challenge Detail
    "challenge.submit": "Enviar Participação",
    "challenge.uploadPhoto": "Enviar Foto/Vídeo",
    "challenge.caption": "Legenda (Opcional)",
    "challenge.yourSubmission": "Seu Envio",
    "challenge.signInToParticipate": "Faça login para participar",
    "challenge.submitting": "Enviando...",
    "challenge.submitted": "Enviado",
    "challenge.editImage": "Editar Imagem",
  },
  ar: {
    // Navigation
    "nav.home": "الرئيسية",
    "nav.challenges": "التحديات",
    "nav.feed": "الخلاصة",
    "nav.leaderboard": "لوحة المتصدرين",
    "nav.profile": "الملف الشخصي",
    "nav.wallet": "المحفظة",
    "nav.referrals": "الإحالات",
    "nav.admin": "لوحة الإدارة",
    "nav.signOut": "تسجيل الخروج",
    "nav.signIn": "تسجيل الدخول",
    "nav.getStarted": "ابدأ الآن",
    
    // Hero
    "hero.badge": "انضم إلى أكثر من 100 ألف مبدع حول العالم",
    "hero.title1": "أنشئ.",
    "hero.title2": "تنافس.",
    "hero.title3": "اربح الكثير.",
    "hero.description": "انضم إلى التحديات الإبداعية اليومية، واكسب النقاط والشارات، وتنافس مع المبدعين من جميع أنحاء العالم، واربح جوائز نقدية حقيقية. لم تكن إبداعاتك بهذه القيمة من قبل!",
    "hero.cta": "ابدأ الإنشاء الآن",
    "hero.howItWorks": "كيف يعمل",
    "hero.prizesWon": "الجوائز المكتسبة",
    "hero.activeUsers": "المستخدمون النشطون",
    "hero.challenges": "التحديات",
    
    // Stats
    "stats.totalPrizes": "إجمالي الجوائز",
    "stats.awardedToCreators": "ممنوحة للمبدعين",
    "stats.activeCreators": "المبدعون النشطون",
    "stats.creatingDaily": "الإنشاء اليومي",
    "stats.dailyChallenges": "التحديات اليومية",
    "stats.newEveryDay": "جديد كل يوم",
    "stats.avgEarnings": "متوسط الأرباح",
    "stats.perMonth": "شهرياً",
    
    // Challenges
    "challenges.featured": "التحديات المميزة",
    "challenges.trending": "انضم إلى هذه التحديات الرائجة وابدأ الكسب اليوم",
    "challenges.joinChallenge": "انضم للتحدي",
    "challenges.participants": "المشاركون",
    "challenges.timeLeft": "الوقت المتبقي",
    "challenges.prize": "الجائزة",
    "challenges.points": "النقاط",
    "challenges.difficulty": "الصعوبة",
    "challenges.easy": "سهل",
    "challenges.medium": "متوسط",
    "challenges.hard": "صعب",
    
    // CTA
    "cta.title": "هل أنت مستعد لتحويل إبداعك إلى نقود؟",
    "cta.description": "انضم إلى آلاف المبدعين الذين يكسبون المال من فعل ما يحبون. سجل الآن واحصل على 100 نقطة مكافأة!",
    "cta.button": "انضم إلى Questify مجاناً",
    
    // Auth
    "auth.login": "تسجيل الدخول",
    "auth.signup": "التسجيل",
    "auth.email": "البريد الإلكتروني",
    "auth.password": "كلمة المرور",
    "auth.username": "اسم المستخدم",
    "auth.displayName": "الاسم المعروض (اختياري)",
    "auth.signIn": "تسجيل الدخول",
    "auth.signInWith": "أو تابع مع",
    "auth.createAccount": "إنشاء حساب",
    "auth.signingIn": "جارٍ تسجيل الدخول...",
    "auth.creatingAccount": "جارٍ إنشاء الحساب...",
    
    // Referrals
    "referrals.title": "برنامج الإحالة",
    "referrals.description": "ادعُ أصدقاءك واكسب المكافآت معاً! احصل على 50 نقطة لكل صديق ينضم، ويحصلون على 25 نقطة.",
    "referrals.totalReferrals": "إجمالي الإحالات",
    "referrals.totalEarnings": "إجمالي الأرباح",
    "referrals.rewardPerReferral": "المكافأة لكل إحالة",
    "referrals.yourCode": "رمز الإحالة الخاص بك",
    "referrals.shareCode": "شارك هذا الرمز مع الأصدقاء لكسب المكافآت",
    "referrals.copyLink": "نسخ الرابط",
    "referrals.share": "مشاركة",
    "referrals.shareOnSocial": "مشاركة على وسائل التواصل",
    "referrals.howItWorks": "كيف يعمل:",
    "referrals.step1": "شارك رمز الإحالة أو الرابط مع الأصدقاء",
    "referrals.step2": "يسجلون باستخدام رمزك ويحصلون على 25 نقطة مكافأة",
    "referrals.step3": "تحصل على 50 نقطة لكل إحالة ناجحة",
    "referrals.history": "سجل الإحالات",
    "referrals.noReferrals": "لا توجد إحالات بعد",
    "referrals.startSharing": "شارك رمز الإحالة الخاص بك لبدء كسب المكافآت!",
    "referrals.joined": "انضم في",
    
    // Common
    "common.loading": "جارٍ التحميل...",
    "common.back": "رجوع",
    "common.save": "حفظ",
    "common.cancel": "إلغاء",
    "common.submit": "إرسال",
    "common.edit": "تعديل",
    "common.delete": "حذف",
    "common.search": "بحث",
    "common.filter": "تصفية",
    "common.sort": "ترتيب",
    
    // Profile
    "profile.myProfile": "ملفي الشخصي",
    "profile.level": "المستوى",
    "profile.followers": "المتابعون",
    "profile.following": "المتابَعون",
    "profile.submissions": "المشاركات",
    "profile.achievements": "الإنجازات",
    "profile.editProfile": "تعديل الملف الشخصي",
    "profile.settings": "الإعدادات",
    
    // Leaderboard
    "leaderboard.title": "لوحة المتصدرين",
    "leaderboard.topCreators": "أفضل المبدعين",
    "leaderboard.rank": "الترتيب",
    "leaderboard.creator": "المبدع",
    "leaderboard.thisWeek": "هذا الأسبوع",
    "leaderboard.allTime": "كل الأوقات",
    
    // Feed
    "feed.title": "الخلاصة",
    "feed.recent": "الأحدث",
    "feed.popular": "الأكثر شعبية",
    "feed.following": "المتابَعون",
    "feed.noSubmissions": "لا توجد مشاركات بعد",
    
    // Wallet
    "wallet.title": "المحفظة",
    "wallet.balance": "الرصيد",
    "wallet.transactions": "المعاملات",
    "wallet.history": "السجل",
    "wallet.topUp": "إعادة الشحن",
    "wallet.withdraw": "سحب",
    
    // Challenge Detail
    "challenge.submit": "إرسال المشاركة",
    "challenge.uploadPhoto": "رفع صورة/فيديو",
    "challenge.caption": "التعليق (اختياري)",
    "challenge.yourSubmission": "مشاركتك",
    "challenge.signInToParticipate": "سجّل الدخول للمشاركة",
    "challenge.submitting": "جارٍ الإرسال...",
    "challenge.submitted": "تم الإرسال",
    "challenge.editImage": "تعديل الصورة",
  },
  he: {
    // Navigation
    "nav.home": "בית",
    "nav.challenges": "אתגרים",
    "nav.feed": "פיד",
    "nav.leaderboard": "לוח מובילים",
    "nav.profile": "פרופיל",
    "nav.wallet": "ארנק",
    "nav.referrals": "הפניות",
    "nav.admin": "פאנל ניהול",
    "nav.signOut": "התנתק",
    "nav.signIn": "התחבר",
    "nav.getStarted": "התחל",
    
    // Hero
    "hero.badge": "הצטרף ליותר מ-100 אלף יוצרים ברחבי העולם",
    "hero.title1": "צור.",
    "hero.title2": "התחרה.",
    "hero.title3": "זכה גדול.",
    "hero.description": "הצטרף לאתגרים יצירתיים יומיים, צבור נקודות ותגים, התחרה עם יוצרים מרחבי העולם וזכה בפרסים כספיים אמיתיים. היצירתיות שלך מעולם לא הייתה כה משתלמת!",
    "hero.cta": "התחל ליצור עכשיו",
    "hero.howItWorks": "איך זה עובד",
    "hero.prizesWon": "פרסים שזכו",
    "hero.activeUsers": "משתמשים פעילים",
    "hero.challenges": "אתגרים",
    
    // Stats
    "stats.totalPrizes": "סה\"כ פרסים",
    "stats.awardedToCreators": "הוענקו ליוצרים",
    "stats.activeCreators": "יוצרים פעילים",
    "stats.creatingDaily": "יוצרים יומיומי",
    "stats.dailyChallenges": "אתגרים יומיים",
    "stats.newEveryDay": "חדש בכל יום",
    "stats.avgEarnings": "הכנסה ממוצעת",
    "stats.perMonth": "לחודש",
    
    // Challenges
    "challenges.featured": "אתגרים מומלצים",
    "challenges.trending": "הצטרף לאתגרים הטרנדיים האלה והתחל להרוויח היום",
    "challenges.joinChallenge": "הצטרף לאתגר",
    "challenges.participants": "משתתפים",
    "challenges.timeLeft": "זמן נותר",
    "challenges.prize": "פרס",
    "challenges.points": "נקודות",
    "challenges.difficulty": "רמת קושי",
    "challenges.easy": "קל",
    "challenges.medium": "בינוני",
    "challenges.hard": "קשה",
    
    // CTA
    "cta.title": "מוכן להפוך את היצירתיות שלך לכסף?",
    "cta.description": "הצטרף לאלפי יוצרים שמרוויחים כסף מעשייה מה שהם אוהבים. הירשם עכשיו וקבל 100 נקודות בונוס!",
    "cta.button": "הצטרף ל-Questify בחינם",
    
    // Auth
    "auth.login": "התחברות",
    "auth.signup": "הרשמה",
    "auth.email": "דוא\"ל",
    "auth.password": "סיסמה",
    "auth.username": "שם משתמש",
    "auth.displayName": "שם תצוגה (אופציונלי)",
    "auth.signIn": "התחבר",
    "auth.signInWith": "או המשך עם",
    "auth.createAccount": "צור חשבון",
    "auth.signingIn": "מתחבר...",
    "auth.creatingAccount": "יוצר חשבון...",
    
    // Referrals
    "referrals.title": "תוכנית הפניות",
    "referrals.description": "הזמן חברים וצבור תגמולים ביחד! קבל 50 נקודות עבור כל חבר שמצטרף, והם מקבלים 25 נקודות.",
    "referrals.totalReferrals": "סה\"כ הפניות",
    "referrals.totalEarnings": "סה\"כ רווחים",
    "referrals.rewardPerReferral": "תגמול להפניה",
    "referrals.yourCode": "קוד ההפניה שלך",
    "referrals.shareCode": "שתף קוד זה עם חברים כדי לצבור תגמולים",
    "referrals.copyLink": "העתק קישור",
    "referrals.share": "שתף",
    "referrals.shareOnSocial": "שתף ברשתות חברתיות",
    "referrals.howItWorks": "איך זה עובד:",
    "referrals.step1": "שתף את קוד ההפניה או הקישור שלך עם חברים",
    "referrals.step2": "הם נרשמים באמצעות הקוד שלך ומקבלים 25 נקודות בונוס",
    "referrals.step3": "אתה מקבל 50 נקודות עבור כל הפניה מוצלחת",
    "referrals.history": "היסטוריית הפניות",
    "referrals.noReferrals": "אין הפניות עדיין",
    "referrals.startSharing": "שתף את קוד ההפניה שלך כדי להתחיל לצבור תגמולים!",
    "referrals.joined": "הצטרף ב",
    
    // Common
    "common.loading": "טוען...",
    "common.back": "חזור",
    "common.save": "שמור",
    "common.cancel": "בטל",
    "common.submit": "שלח",
    "common.edit": "ערוך",
    "common.delete": "מחק",
    "common.search": "חפש",
    "common.filter": "סנן",
    "common.sort": "מיין",
    
    // Profile
    "profile.myProfile": "הפרופיל שלי",
    "profile.level": "רמה",
    "profile.followers": "עוקבים",
    "profile.following": "עוקב",
    "profile.submissions": "שיתופים",
    "profile.achievements": "הישגים",
    "profile.editProfile": "ערוך פרופיל",
    "profile.settings": "הגדרות",
    
    // Leaderboard
    "leaderboard.title": "לוח מובילים",
    "leaderboard.topCreators": "יוצרים מובילים",
    "leaderboard.rank": "דירוג",
    "leaderboard.creator": "יוצר",
    "leaderboard.thisWeek": "השבוע",
    "leaderboard.allTime": "כל הזמנים",
    
    // Feed
    "feed.title": "פיד",
    "feed.recent": "אחרונים",
    "feed.popular": "פופולריים",
    "feed.following": "עוקבים",
    "feed.noSubmissions": "אין שיתופים עדיין",
    
    // Wallet
    "wallet.title": "ארנק",
    "wallet.balance": "יתרה",
    "wallet.transactions": "עסקאות",
    "wallet.history": "היסטוריה",
    "wallet.topUp": "טען",
    "wallet.withdraw": "משוך",
    
    // Challenge Detail
    "challenge.submit": "שלח שיתוף",
    "challenge.uploadPhoto": "העלה תמונה/וידאו",
    "challenge.caption": "כותרת (אופציונלי)",
    "challenge.yourSubmission": "השיתוף שלך",
    "challenge.signInToParticipate": "התחבר כדי להשתתף",
    "challenge.submitting": "שולח...",
    "challenge.submitted": "נשלח",
    "challenge.editImage": "ערוך תמונה",
  },
  it: {
    "nav.home": "Home",
    "nav.challenges": "Sfide",
    "nav.feed": "Feed",
    "nav.leaderboard": "Classifica",
    "nav.profile": "Profilo",
    "nav.wallet": "Portafoglio",
    "nav.referrals": "Referral",
    "nav.admin": "Pannello Admin",
    "nav.signOut": "Esci",
    "nav.signIn": "Accedi",
    "nav.getStarted": "Inizia",
    
    "hero.badge": "Unisciti a 100k+ Creatori in Tutto il Mondo",
    "hero.title1": "Crea.",
    "hero.title2": "Competi.",
    "hero.title3": "Vinci Alla Grande.",
    "hero.description": "Partecipa a sfide creative quotidiane, guadagna punti e badge, competi con creatori di tutto il mondo e vinci premi in denaro reale. La tua creatività non è mai stata così gratificante!",
    "hero.cta": "Inizia a Creare Ora",
    "hero.howItWorks": "Come Funziona",
    "hero.prizesWon": "Premi Vinti",
    "hero.activeUsers": "Utenti Attivi",
    "hero.challenges": "Sfide",
    
    "stats.totalPrizes": "Premi Totali",
    "stats.awardedToCreators": "Assegnati ai creatori",
    "stats.activeCreators": "Creatori Attivi",
    "stats.creatingDaily": "Creando quotidianamente",
    "stats.dailyChallenges": "Sfide Giornaliere",
    "stats.newEveryDay": "Nuove ogni giorno",
    "stats.avgEarnings": "Guadagni Medi",
    "stats.perMonth": "Al mese",
    
    "challenges.featured": "Sfide in Evidenza",
    "challenges.trending": "Unisciti a queste sfide di tendenza e inizia a guadagnare oggi",
    "challenges.joinChallenge": "Unisciti alla Sfida",
    "challenges.participants": "Partecipanti",
    "challenges.timeLeft": "Tempo Rimasto",
    "challenges.prize": "Premio",
    "challenges.points": "Punti",
    "challenges.difficulty": "Difficoltà",
    "challenges.easy": "Facile",
    "challenges.medium": "Medio",
    "challenges.hard": "Difficile",
    
    "cta.title": "Pronto a Trasformare la Tua Creatività in Denaro?",
    "cta.description": "Unisciti a migliaia di creatori che guadagnano facendo ciò che amano. Iscriviti ora e ottieni 100 punti bonus!",
    "cta.button": "Unisciti a Questify Gratis",
    
    "auth.login": "Accedi",
    "auth.signup": "Registrati",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.username": "Nome Utente",
    "auth.displayName": "Nome Visualizzato (Opzionale)",
    "auth.signIn": "Accedi",
    "auth.signInWith": "Oppure continua con",
    "auth.createAccount": "Crea Account",
    "auth.signingIn": "Accesso in corso...",
    "auth.creatingAccount": "Creazione account...",
    
    "referrals.title": "Programma Referral",
    "referrals.description": "Invita amici e guadagna premi insieme! Ottieni 50 punti per ogni amico che si unisce, e loro ricevono 25 punti.",
    "referrals.totalReferrals": "Referral Totali",
    "referrals.totalEarnings": "Guadagni Totali",
    "referrals.rewardPerReferral": "Ricompensa per Referral",
    "referrals.yourCode": "Il Tuo Codice Referral",
    "referrals.shareCode": "Condividi questo codice con gli amici per guadagnare premi",
    "referrals.copyLink": "Copia Link",
    "referrals.share": "Condividi",
    "referrals.shareOnSocial": "Condividi sui social media",
    "referrals.howItWorks": "Come funziona:",
    "referrals.step1": "Condividi il tuo codice o link referral con gli amici",
    "referrals.step2": "Si registrano usando il tuo codice e ottengono 25 punti bonus",
    "referrals.step3": "Ricevi 50 punti per ogni referral riuscito",
    "referrals.history": "Cronologia Referral",
    "referrals.noReferrals": "Nessun referral ancora",
    "referrals.startSharing": "Condividi il tuo codice referral per iniziare a guadagnare premi!",
    "referrals.joined": "Iscritto",
    
    "common.loading": "Caricamento...",
    "common.back": "Indietro",
    "common.save": "Salva",
    "common.cancel": "Annulla",
    "common.submit": "Invia",
    "common.edit": "Modifica",
    "common.delete": "Elimina",
    "common.search": "Cerca",
    "common.filter": "Filtra",
    "common.sort": "Ordina",
    
    // Profile
    "profile.myProfile": "Il Mio Profilo",
    "profile.level": "Livello",
    "profile.followers": "Follower",
    "profile.following": "Following",
    "profile.submissions": "Invii",
    "profile.achievements": "Obiettivi",
    "profile.editProfile": "Modifica Profilo",
    "profile.settings": "Impostazioni",
    
    // Leaderboard
    "leaderboard.title": "Classifica",
    "leaderboard.topCreators": "Top Creatori",
    "leaderboard.rank": "Posizione",
    "leaderboard.creator": "Creatore",
    "leaderboard.thisWeek": "Questa Settimana",
    "leaderboard.allTime": "Tutti i Tempi",
    
    // Feed
    "feed.title": "Feed",
    "feed.recent": "Recenti",
    "feed.popular": "Popolari",
    "feed.following": "Following",
    "feed.noSubmissions": "Nessun invio ancora",
    
    // Wallet
    "wallet.title": "Portafoglio",
    "wallet.balance": "Saldo",
    "wallet.transactions": "Transazioni",
    "wallet.history": "Cronologia",
    "wallet.topUp": "Ricarica",
    "wallet.withdraw": "Preleva",
    
    // Challenge Detail
    "challenge.submit": "Invia Partecipazione",
    "challenge.uploadPhoto": "Carica Foto/Video",
    "challenge.caption": "Didascalia (Opzionale)",
    "challenge.yourSubmission": "Il Tuo Invio",
    "challenge.signInToParticipate": "Accedi per partecipare",
    "challenge.submitting": "Invio...",
    "challenge.submitted": "Inviato",
    "challenge.editImage": "Modifica Immagine",
  },
  ja: {
    "nav.home": "ホーム",
    "nav.challenges": "チャレンジ",
    "nav.feed": "フィード",
    "nav.leaderboard": "リーダーボード",
    "nav.profile": "プロフィール",
    "nav.wallet": "ウォレット",
    "nav.referrals": "紹介",
    "nav.admin": "管理パネル",
    "nav.signOut": "ログアウト",
    "nav.signIn": "ログイン",
    "nav.getStarted": "始める",
    
    "hero.badge": "世界中の10万人以上のクリエイターに参加",
    "hero.title1": "作成。",
    "hero.title2": "競争。",
    "hero.title3": "大勝利。",
    "hero.description": "毎日のクリエイティブチャレンジに参加し、ポイントとバッジを獲得し、世界中のクリエイターと競い合い、本物の賞金を獲得しましょう。あなたの創造性がこれほどまでに報われることはありませんでした！",
    "hero.cta": "今すぐ作成を開始",
    "hero.howItWorks": "仕組み",
    "hero.prizesWon": "獲得賞金",
    "hero.activeUsers": "アクティブユーザー",
    "hero.challenges": "チャレンジ",
    
    "stats.totalPrizes": "総賞金",
    "stats.awardedToCreators": "クリエイターに授与",
    "stats.activeCreators": "アクティブクリエイター",
    "stats.creatingDaily": "毎日作成",
    "stats.dailyChallenges": "デイリーチャレンジ",
    "stats.newEveryDay": "毎日新しい",
    "stats.avgEarnings": "平均収益",
    "stats.perMonth": "月間",
    
    "challenges.featured": "注目のチャレンジ",
    "challenges.trending": "これらのトレンドチャレンジに参加して、今日から稼ぎましょう",
    "challenges.joinChallenge": "チャレンジに参加",
    "challenges.participants": "参加者",
    "challenges.timeLeft": "残り時間",
    "challenges.prize": "賞品",
    "challenges.points": "ポイント",
    "challenges.difficulty": "難易度",
    "challenges.easy": "簡単",
    "challenges.medium": "普通",
    "challenges.hard": "難しい",
    
    "cta.title": "創造性をお金に変える準備はできましたか？",
    "cta.description": "好きなことをしてお金を稼いでいる何千ものクリエイターに参加しましょう。今すぐサインアップして100ボーナスポイントを獲得！",
    "cta.button": "Questifyに無料参加",
    
    "auth.login": "ログイン",
    "auth.signup": "サインアップ",
    "auth.email": "メール",
    "auth.password": "パスワード",
    "auth.username": "ユーザー名",
    "auth.displayName": "表示名（オプション）",
    "auth.signIn": "サインイン",
    "auth.signInWith": "または続行",
    "auth.createAccount": "アカウント作成",
    "auth.signingIn": "サインイン中...",
    "auth.creatingAccount": "アカウント作成中...",
    
    "referrals.title": "紹介プログラム",
    "referrals.description": "友達を招待して一緒に報酬を獲得しましょう！参加した友達1人につき50ポイント獲得し、彼らは25ポイント獲得します。",
    "referrals.totalReferrals": "総紹介数",
    "referrals.totalEarnings": "総収益",
    "referrals.rewardPerReferral": "紹介ごとの報酬",
    "referrals.yourCode": "あなたの紹介コード",
    "referrals.shareCode": "このコードを友達と共有して報酬を獲得",
    "referrals.copyLink": "リンクをコピー",
    "referrals.share": "共有",
    "referrals.shareOnSocial": "ソーシャルメディアで共有",
    "referrals.howItWorks": "仕組み：",
    "referrals.step1": "紹介コードまたはリンクを友達と共有",
    "referrals.step2": "彼らがあなたのコードを使用してサインアップし、25ボーナスポイント獲得",
    "referrals.step3": "成功した紹介ごとに50ポイント獲得",
    "referrals.history": "紹介履歴",
    "referrals.noReferrals": "まだ紹介はありません",
    "referrals.startSharing": "紹介コードを共有して報酬を獲得しましょう！",
    "referrals.joined": "参加日",
    
    "common.loading": "読み込み中...",
    "common.back": "戻る",
    "common.save": "保存",
    "common.cancel": "キャンセル",
    "common.submit": "送信",
    "common.edit": "編集",
    "common.delete": "削除",
    "common.search": "検索",
    "common.filter": "フィルター",
    "common.sort": "並び替え",
    
    // Profile
    "profile.myProfile": "マイプロフィール",
    "profile.level": "レベル",
    "profile.followers": "フォロワー",
    "profile.following": "フォロー中",
    "profile.submissions": "投稿",
    "profile.achievements": "達成",
    "profile.editProfile": "プロフィール編集",
    "profile.settings": "設定",
    
    // Leaderboard
    "leaderboard.title": "リーダーボード",
    "leaderboard.topCreators": "トップクリエイター",
    "leaderboard.rank": "ランク",
    "leaderboard.creator": "クリエイター",
    "leaderboard.thisWeek": "今週",
    "leaderboard.allTime": "全期間",
    
    // Feed
    "feed.title": "フィード",
    "feed.recent": "最新",
    "feed.popular": "人気",
    "feed.following": "フォロー中",
    "feed.noSubmissions": "まだ投稿はありません",
    
    // Wallet
    "wallet.title": "ウォレット",
    "wallet.balance": "残高",
    "wallet.transactions": "取引",
    "wallet.history": "履歴",
    "wallet.topUp": "チャージ",
    "wallet.withdraw": "出金",
    
    // Challenge Detail
    "challenge.submit": "投稿を送信",
    "challenge.uploadPhoto": "写真/動画をアップロード",
    "challenge.caption": "キャプション（オプション）",
    "challenge.yourSubmission": "あなたの投稿",
    "challenge.signInToParticipate": "参加するにはサインイン",
    "challenge.submitting": "送信中...",
    "challenge.submitted": "送信済み",
    "challenge.editImage": "画像を編集",
  },
  ko: {
    "nav.home": "홈",
    "nav.challenges": "챌린지",
    "nav.feed": "피드",
    "nav.leaderboard": "리더보드",
    "nav.profile": "프로필",
    "nav.wallet": "지갑",
    "nav.referrals": "추천",
    "nav.admin": "관리자 패널",
    "nav.signOut": "로그아웃",
    "nav.signIn": "로그인",
    "nav.getStarted": "시작하기",
    
    "hero.badge": "전 세계 10만 명 이상의 크리에이터와 함께하세요",
    "hero.title1": "창작.",
    "hero.title2": "경쟁.",
    "hero.title3": "큰 승리.",
    "hero.description": "일일 창의적 챌린지에 참여하고, 포인트와 배지를 획득하며, 전 세계 크리에이터들과 경쟁하고, 실제 현금 상금을 받으세요. 당신의 창의성이 이렇게 보람 있었던 적이 없었습니다!",
    "hero.cta": "지금 창작 시작",
    "hero.howItWorks": "작동 방식",
    "hero.prizesWon": "획득한 상금",
    "hero.activeUsers": "활성 사용자",
    "hero.challenges": "챌린지",
    
    "stats.totalPrizes": "총 상금",
    "stats.awardedToCreators": "크리에이터에게 수여",
    "stats.activeCreators": "활성 크리에이터",
    "stats.creatingDaily": "매일 창작",
    "stats.dailyChallenges": "일일 챌린지",
    "stats.newEveryDay": "매일 새로운",
    "stats.avgEarnings": "평균 수익",
    "stats.perMonth": "월간",
    
    "challenges.featured": "추천 챌린지",
    "challenges.trending": "이 트렌딩 챌린지에 참여하고 오늘부터 수익을 얻으세요",
    "challenges.joinChallenge": "챌린지 참여",
    "challenges.participants": "참가자",
    "challenges.timeLeft": "남은 시간",
    "challenges.prize": "상금",
    "challenges.points": "포인트",
    "challenges.difficulty": "난이도",
    "challenges.easy": "쉬움",
    "challenges.medium": "보통",
    "challenges.hard": "어려움",
    
    "cta.title": "창의성을 현금으로 바꿀 준비가 되셨나요?",
    "cta.description": "좋아하는 일을 하면서 돈을 버는 수천 명의 크리에이터와 함께하세요. 지금 가입하고 100 보너스 포인트를 받으세요!",
    "cta.button": "Questify 무료 가입",
    
    "auth.login": "로그인",
    "auth.signup": "회원가입",
    "auth.email": "이메일",
    "auth.password": "비밀번호",
    "auth.username": "사용자 이름",
    "auth.displayName": "표시 이름 (선택사항)",
    "auth.signIn": "로그인",
    "auth.signInWith": "또는 계속",
    "auth.createAccount": "계정 만들기",
    "auth.signingIn": "로그인 중...",
    "auth.creatingAccount": "계정 생성 중...",
    
    "referrals.title": "추천 프로그램",
    "referrals.description": "친구를 초대하고 함께 보상을 받으세요! 가입한 친구 1명당 50포인트를 받고, 그들은 25포인트를 받습니다.",
    "referrals.totalReferrals": "총 추천 수",
    "referrals.totalEarnings": "총 수익",
    "referrals.rewardPerReferral": "추천당 보상",
    "referrals.yourCode": "내 추천 코드",
    "referrals.shareCode": "이 코드를 친구와 공유하여 보상을 받으세요",
    "referrals.copyLink": "링크 복사",
    "referrals.share": "공유",
    "referrals.shareOnSocial": "소셜 미디어에 공유",
    "referrals.howItWorks": "작동 방식:",
    "referrals.step1": "추천 코드나 링크를 친구와 공유",
    "referrals.step2": "그들이 코드로 가입하고 25 보너스 포인트 획득",
    "referrals.step3": "성공한 추천마다 50포인트 획득",
    "referrals.history": "추천 기록",
    "referrals.noReferrals": "아직 추천 없음",
    "referrals.startSharing": "추천 코드를 공유하여 보상을 받으세요!",
    "referrals.joined": "가입일",
    
    "common.loading": "로딩 중...",
    "common.back": "뒤로",
    "common.save": "저장",
    "common.cancel": "취소",
    "common.submit": "제출",
    "common.edit": "편집",
    "common.delete": "삭제",
    "common.search": "검색",
    "common.filter": "필터",
    "common.sort": "정렬",
    
    // Profile
    "profile.myProfile": "내 프로필",
    "profile.level": "레벨",
    "profile.followers": "팔로워",
    "profile.following": "팔로잉",
    "profile.submissions": "제출물",
    "profile.achievements": "업적",
    "profile.editProfile": "프로필 편집",
    "profile.settings": "설정",
    
    // Leaderboard
    "leaderboard.title": "리더보드",
    "leaderboard.topCreators": "상위 크리에이터",
    "leaderboard.rank": "순위",
    "leaderboard.creator": "크리에이터",
    "leaderboard.thisWeek": "이번 주",
    "leaderboard.allTime": "전체 기간",
    
    // Feed
    "feed.title": "피드",
    "feed.recent": "최신",
    "feed.popular": "인기",
    "feed.following": "팔로잉",
    "feed.noSubmissions": "아직 제출물 없음",
    
    // Wallet
    "wallet.title": "지갑",
    "wallet.balance": "잔액",
    "wallet.transactions": "거래",
    "wallet.history": "내역",
    "wallet.topUp": "충전",
    "wallet.withdraw": "출금",
    
    // Challenge Detail
    "challenge.submit": "제출하기",
    "challenge.uploadPhoto": "사진/동영상 업로드",
    "challenge.caption": "캡션 (선택사항)",
    "challenge.yourSubmission": "내 제출물",
    "challenge.signInToParticipate": "참여하려면 로그인",
    "challenge.submitting": "제출 중...",
    "challenge.submitted": "제출됨",
    "challenge.editImage": "이미지 편집",
  },
  zh: {
    "nav.home": "首页",
    "nav.challenges": "挑战",
    "nav.feed": "动态",
    "nav.leaderboard": "排行榜",
    "nav.profile": "个人资料",
    "nav.wallet": "钱包",
    "nav.referrals": "推荐",
    "nav.admin": "管理面板",
    "nav.signOut": "登出",
    "nav.signIn": "登录",
    "nav.getStarted": "开始",
    
    "hero.badge": "加入全球10万多名创作者",
    "hero.title1": "创作。",
    "hero.title2": "竞争。",
    "hero.title3": "赢大奖。",
    "hero.description": "参加每日创意挑战，赚取积分和徽章，与全球创作者竞争，赢取真实现金奖励。你的创造力从未如此有价值！",
    "hero.cta": "立即开始创作",
    "hero.howItWorks": "如何运作",
    "hero.prizesWon": "已获奖金",
    "hero.activeUsers": "活跃用户",
    "hero.challenges": "挑战",
    
    "stats.totalPrizes": "总奖金",
    "stats.awardedToCreators": "授予创作者",
    "stats.activeCreators": "活跃创作者",
    "stats.creatingDaily": "每日创作",
    "stats.dailyChallenges": "每日挑战",
    "stats.newEveryDay": "每天更新",
    "stats.avgEarnings": "平均收益",
    "stats.perMonth": "每月",
    
    "challenges.featured": "精选挑战",
    "challenges.trending": "加入这些热门挑战，今天就开始赚钱",
    "challenges.joinChallenge": "加入挑战",
    "challenges.participants": "参与者",
    "challenges.timeLeft": "剩余时间",
    "challenges.prize": "奖金",
    "challenges.points": "积分",
    "challenges.difficulty": "难度",
    "challenges.easy": "简单",
    "challenges.medium": "中等",
    "challenges.hard": "困难",
    
    "cta.title": "准备好把创造力变成现金了吗？",
    "cta.description": "加入数千名通过做自己喜欢的事赚钱的创作者。立即注册并获得100积分奖励！",
    "cta.button": "免费加入Questify",
    
    "auth.login": "登录",
    "auth.signup": "注册",
    "auth.email": "邮箱",
    "auth.password": "密码",
    "auth.username": "用户名",
    "auth.displayName": "显示名称（可选）",
    "auth.signIn": "登录",
    "auth.signInWith": "或继续使用",
    "auth.createAccount": "创建账户",
    "auth.signingIn": "登录中...",
    "auth.creatingAccount": "创建账户中...",
    
    "referrals.title": "推荐计划",
    "referrals.description": "邀请朋友，一起赚取奖励！每邀请一位朋友加入获得50积分，他们获得25积分。",
    "referrals.totalReferrals": "总推荐数",
    "referrals.totalEarnings": "总收益",
    "referrals.rewardPerReferral": "每次推荐奖励",
    "referrals.yourCode": "你的推荐码",
    "referrals.shareCode": "与朋友分享此代码以赚取奖励",
    "referrals.copyLink": "复制链接",
    "referrals.share": "分享",
    "referrals.shareOnSocial": "在社交媒体上分享",
    "referrals.howItWorks": "如何运作：",
    "referrals.step1": "与朋友分享你的推荐码或链接",
    "referrals.step2": "他们使用你的代码注册并获得25积分奖励",
    "referrals.step3": "每成功推荐一人，你获得50积分",
    "referrals.history": "推荐历史",
    "referrals.noReferrals": "暂无推荐",
    "referrals.startSharing": "分享你的推荐码开始赚取奖励！",
    "referrals.joined": "加入于",
    
    "common.loading": "加载中...",
    "common.back": "返回",
    "common.save": "保存",
    "common.cancel": "取消",
    "common.submit": "提交",
    "common.edit": "编辑",
    "common.delete": "删除",
    "common.search": "搜索",
    "common.filter": "筛选",
    "common.sort": "排序",
    
    // Profile
    "profile.myProfile": "我的个人资料",
    "profile.level": "等级",
    "profile.followers": "粉丝",
    "profile.following": "关注",
    "profile.submissions": "提交",
    "profile.achievements": "成就",
    "profile.editProfile": "编辑个人资料",
    "profile.settings": "设置",
    "profile.stats": "统计",
    "profile.badges": "徽章",
    "profile.saveChanges": "保存更改",
    "profile.displayName": "显示名称",
    "profile.bio": "个人简介",
    "profile.changeAvatar": "更换头像",
    "profile.subscribe": "订阅",
    "profile.manageSubscription": "管理订阅",
    "profile.creatorPassActive": "创作者通行证激活",
    "profile.renewsOn": "续订于",
    "profile.noBadges": "暂无徽章",
    "profile.noSubmissions": "暂无提交",
    
    // Leaderboard
    "leaderboard.title": "排行榜",
    "leaderboard.topCreators": "顶级创作者",
    "leaderboard.rank": "排名",
    "leaderboard.creator": "创作者",
    "leaderboard.thisWeek": "本周",
    "leaderboard.allTime": "全部时间",
    
    // Feed
    "feed.title": "动态",
    "feed.recent": "最新",
    "feed.popular": "热门",
    "feed.following": "关注",
    "feed.noSubmissions": "暂无提交",
    
    // Wallet
    "wallet.title": "钱包",
    "wallet.subtitle": "管理你的余额和订阅",
    "wallet.balance": "余额",
    "wallet.currentBalance": "当前余额",
    "wallet.creatorPass": "创作者通行证",
    "wallet.premiumSubscription": "高级订阅额外福利",
    "wallet.subscribeNow": "立即订阅",
    "wallet.active": "激活",
    "wallet.transactions": "交易历史",
    "wallet.recentActivity": "最近的钱包活动",
    "wallet.history": "历史",
    "wallet.topUp": "充值",
    "wallet.withdraw": "提现",
    "wallet.noTransactions": "暂无交易",
    
    // Challenge Detail
    "challenge.submit": "提交作品",
    "challenge.uploadPhoto": "上传照片/视频",
    "challenge.caption": "说明（可选）",
    "challenge.yourSubmission": "你的提交",
    "challenge.signInToParticipate": "登录以参与",
    "challenge.submitting": "提交中...",
    "challenge.submitted": "已提交",
    "challenge.editImage": "编辑图片",
  },
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("questify-language");
    if (saved) return saved as Language;
    
    // Auto-detect browser language
    const browserLang = navigator.language.split("-")[0];
    const supportedLang = browserLang as Language;
    
    if (["en", "es", "fr", "de", "pt", "it", "ja", "ko", "zh", "ar", "he"].includes(supportedLang)) {
      return supportedLang;
    }
    
    return "en";
  });

  useEffect(() => {
    localStorage.setItem("questify-language", language);
    
    // Set document direction for RTL languages
    document.documentElement.dir = RTL_LANGUAGES.includes(language) ? "rtl" : "ltr";
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  const isRTL = RTL_LANGUAGES.includes(language);

  return (
    <LanguageContext.Provider value={{ language, setLanguage: setLanguageState, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
