import { createContext, useContext, useState, ReactNode, useEffect } from "react";

export type Language = "en" | "es" | "fr" | "de" | "pt" | "it" | "ja" | "ko" | "zh";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    "nav.home": "Home",
    "nav.challenges": "Challenges",
    "nav.feed": "Feed",
    "nav.leaderboard": "Leaderboard",
    "nav.profile": "Profile",
    "nav.wallet": "Wallet",
    "nav.referrals": "Referrals",
    "nav.admin": "Admin Panel",
    "nav.signOut": "Sign Out",
    "nav.signIn": "Sign In",
    "nav.getStarted": "Get Started",
    
    // Hero Section
    "hero.badge": "Join 100k+ Creators Worldwide",
    "hero.title1": "Create.",
    "hero.title2": "Compete.",
    "hero.title3": "Win Big.",
    "hero.description": "Join daily creative challenges, earn points and badges, compete with creators worldwide, and win real cash prizes. Your creativity has never been this rewarding!",
    "hero.cta": "Start Creating Now",
    "hero.howItWorks": "See How It Works",
    "hero.prizesWon": "Prizes Won",
    "hero.activeUsers": "Active Users",
    "hero.challenges": "Challenges",
    
    // Stats
    "stats.totalPrizes": "Total Prizes",
    "stats.awardedToCreators": "Awarded to creators",
    "stats.activeCreators": "Active Creators",
    "stats.creatingDaily": "Creating daily",
    "stats.dailyChallenges": "Daily Challenges",
    "stats.newEveryDay": "New every day",
    "stats.avgEarnings": "Avg Earnings",
    "stats.perMonth": "Per month",
    
    // Challenges
    "challenges.featured": "Featured Challenges",
    "challenges.trending": "Join these trending challenges and start earning today",
    "challenges.joinChallenge": "Join Challenge",
    "challenges.participants": "Participants",
    "challenges.timeLeft": "Time Left",
    "challenges.prize": "Prize",
    "challenges.points": "Points",
    "challenges.difficulty": "Difficulty",
    "challenges.easy": "Easy",
    "challenges.medium": "Medium",
    "challenges.hard": "Hard",
    
    // CTA
    "cta.title": "Ready to Turn Your Creativity Into Cash?",
    "cta.description": "Join thousands of creators earning money doing what they love. Sign up now and get 100 bonus points!",
    "cta.button": "Join Questify Free",
    
    // Auth
    "auth.login": "Login",
    "auth.signup": "Sign Up",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.username": "Username",
    "auth.displayName": "Display Name (Optional)",
    "auth.signIn": "Sign In",
    "auth.signInWith": "Or continue with",
    "auth.createAccount": "Create Account",
    "auth.signingIn": "Signing in...",
    "auth.creatingAccount": "Creating account...",
    
    // Referrals
    "referrals.title": "Referral Program",
    "referrals.description": "Invite friends and earn rewards together! Get 50 points for each friend who joins, and they get 25 points.",
    "referrals.totalReferrals": "Total Referrals",
    "referrals.totalEarnings": "Total Earnings",
    "referrals.rewardPerReferral": "Reward Per Referral",
    "referrals.yourCode": "Your Referral Code",
    "referrals.shareCode": "Share this code with friends to earn rewards",
    "referrals.copyLink": "Copy Link",
    "referrals.share": "Share",
    "referrals.shareOnSocial": "Share on social media",
    "referrals.howItWorks": "How it works:",
    "referrals.step1": "Share your referral code or link with friends",
    "referrals.step2": "They sign up using your code and get 25 bonus points",
    "referrals.step3": "You receive 50 points for each successful referral",
    "referrals.history": "Referral History",
    "referrals.noReferrals": "No referrals yet",
    "referrals.startSharing": "Share your referral code to start earning rewards!",
    "referrals.joined": "Joined",
    
    // Common
    "common.loading": "Loading...",
    "common.back": "Back",
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.submit": "Submit",
    "common.edit": "Edit",
    "common.delete": "Delete",
    "common.search": "Search",
    "common.filter": "Filter",
    "common.sort": "Sort",
  },
  es: {
    // Navigation
    "nav.home": "Inicio",
    "nav.challenges": "Desafíos",
    "nav.feed": "Feed",
    "nav.leaderboard": "Clasificación",
    "nav.profile": "Perfil",
    "nav.wallet": "Cartera",
    "nav.referrals": "Referencias",
    "nav.admin": "Panel Admin",
    "nav.signOut": "Cerrar Sesión",
    "nav.signIn": "Iniciar Sesión",
    "nav.getStarted": "Comenzar",
    
    // Hero
    "hero.badge": "Únete a 100k+ Creadores en Todo el Mundo",
    "hero.title1": "Crea.",
    "hero.title2": "Compite.",
    "hero.title3": "Gana en Grande.",
    "hero.description": "Únete a desafíos creativos diarios, gana puntos y medallas, compite con creadores de todo el mundo y gana premios en efectivo reales. ¡Tu creatividad nunca ha sido tan gratificante!",
    "hero.cta": "Comienza a Crear Ahora",
    "hero.howItWorks": "Cómo Funciona",
    "hero.prizesWon": "Premios Ganados",
    "hero.activeUsers": "Usuarios Activos",
    "hero.challenges": "Desafíos",
    
    // Stats
    "stats.totalPrizes": "Premios Totales",
    "stats.awardedToCreators": "Otorgados a creadores",
    "stats.activeCreators": "Creadores Activos",
    "stats.creatingDaily": "Creando diariamente",
    "stats.dailyChallenges": "Desafíos Diarios",
    "stats.newEveryDay": "Nuevos cada día",
    "stats.avgEarnings": "Ganancias Promedio",
    "stats.perMonth": "Por mes",
    
    // Challenges
    "challenges.featured": "Desafíos Destacados",
    "challenges.trending": "Únete a estos desafíos populares y comienza a ganar hoy",
    "challenges.joinChallenge": "Unirse al Desafío",
    "challenges.participants": "Participantes",
    "challenges.timeLeft": "Tiempo Restante",
    "challenges.prize": "Premio",
    "challenges.points": "Puntos",
    "challenges.difficulty": "Dificultad",
    "challenges.easy": "Fácil",
    "challenges.medium": "Medio",
    "challenges.hard": "Difícil",
    
    // CTA
    "cta.title": "¿Listo para Convertir tu Creatividad en Dinero?",
    "cta.description": "Únete a miles de creadores ganando dinero haciendo lo que aman. ¡Regístrate ahora y obtén 100 puntos de bonificación!",
    "cta.button": "Únete a Questify Gratis",
    
    // Auth
    "auth.login": "Iniciar Sesión",
    "auth.signup": "Registrarse",
    "auth.email": "Correo Electrónico",
    "auth.password": "Contraseña",
    "auth.username": "Nombre de Usuario",
    "auth.displayName": "Nombre para Mostrar (Opcional)",
    "auth.signIn": "Iniciar Sesión",
    "auth.signInWith": "O continuar con",
    "auth.createAccount": "Crear Cuenta",
    "auth.signingIn": "Iniciando sesión...",
    "auth.creatingAccount": "Creando cuenta...",
    
    // Referrals
    "referrals.title": "Programa de Referencias",
    "referrals.description": "¡Invita amigos y gana recompensas juntos! Obtén 50 puntos por cada amigo que se una, y ellos reciben 25 puntos.",
    "referrals.totalReferrals": "Referencias Totales",
    "referrals.totalEarnings": "Ganancias Totales",
    "referrals.rewardPerReferral": "Recompensa por Referencia",
    "referrals.yourCode": "Tu Código de Referencia",
    "referrals.shareCode": "Comparte este código con amigos para ganar recompensas",
    "referrals.copyLink": "Copiar Enlace",
    "referrals.share": "Compartir",
    "referrals.shareOnSocial": "Compartir en redes sociales",
    "referrals.howItWorks": "Cómo funciona:",
    "referrals.step1": "Comparte tu código de referencia o enlace con amigos",
    "referrals.step2": "Se registran usando tu código y obtienen 25 puntos de bonificación",
    "referrals.step3": "Recibes 50 puntos por cada referencia exitosa",
    "referrals.history": "Historial de Referencias",
    "referrals.noReferrals": "Aún no hay referencias",
    "referrals.startSharing": "¡Comparte tu código de referencia para comenzar a ganar recompensas!",
    "referrals.joined": "Se unió",
    
    // Common
    "common.loading": "Cargando...",
    "common.back": "Atrás",
    "common.save": "Guardar",
    "common.cancel": "Cancelar",
    "common.submit": "Enviar",
    "common.edit": "Editar",
    "common.delete": "Eliminar",
    "common.search": "Buscar",
    "common.filter": "Filtrar",
    "common.sort": "Ordenar",
  },
  fr: {
    "nav.home": "Accueil",
    "nav.challenges": "Défis",
    "nav.feed": "Fil",
    "nav.leaderboard": "Classement",
    "nav.profile": "Profil",
    "nav.wallet": "Portefeuille",
    "nav.referrals": "Parrainages",
    "nav.admin": "Panel Admin",
    "nav.signOut": "Déconnexion",
    "nav.signIn": "Connexion",
    "nav.getStarted": "Commencer",
    
    "hero.badge": "Rejoignez 100k+ Créateurs dans le Monde",
    "hero.title1": "Créer.",
    "hero.title2": "Compétitionner.",
    "hero.title3": "Gagner Gros.",
    "hero.description": "Participez à des défis créatifs quotidiens, gagnez des points et des badges, affrontez des créateurs du monde entier et remportez de vrais prix en espèces. Votre créativité n'a jamais été aussi gratifiante !",
    "hero.cta": "Commencer à Créer",
    "hero.howItWorks": "Comment Ça Marche",
    "hero.prizesWon": "Prix Gagnés",
    "hero.activeUsers": "Utilisateurs Actifs",
    "hero.challenges": "Défis",
    
    "stats.totalPrizes": "Prix Totaux",
    "stats.awardedToCreators": "Attribués aux créateurs",
    "stats.activeCreators": "Créateurs Actifs",
    "stats.creatingDaily": "Créant quotidiennement",
    "stats.dailyChallenges": "Défis Quotidiens",
    "stats.newEveryDay": "Nouveaux chaque jour",
    "stats.avgEarnings": "Gains Moyens",
    "stats.perMonth": "Par mois",
    
    "challenges.featured": "Défis en Vedette",
    "challenges.trending": "Rejoignez ces défis tendance et commencez à gagner aujourd'hui",
    "challenges.joinChallenge": "Rejoindre le Défi",
    "challenges.participants": "Participants",
    "challenges.timeLeft": "Temps Restant",
    "challenges.prize": "Prix",
    "challenges.points": "Points",
    "challenges.difficulty": "Difficulté",
    "challenges.easy": "Facile",
    "challenges.medium": "Moyen",
    "challenges.hard": "Difficile",
    
    "cta.title": "Prêt à Transformer Votre Créativité en Argent ?",
    "cta.description": "Rejoignez des milliers de créateurs gagnant de l'argent en faisant ce qu'ils aiment. Inscrivez-vous maintenant et obtenez 100 points bonus !",
    "cta.button": "Rejoindre Questify Gratuitement",
    
    "auth.login": "Connexion",
    "auth.signup": "S'inscrire",
    "auth.email": "Email",
    "auth.password": "Mot de passe",
    "auth.username": "Nom d'utilisateur",
    "auth.displayName": "Nom d'affichage (Optionnel)",
    "auth.signIn": "Se Connecter",
    "auth.signInWith": "Ou continuer avec",
    "auth.createAccount": "Créer un Compte",
    "auth.signingIn": "Connexion...",
    "auth.creatingAccount": "Création du compte...",
    
    "referrals.title": "Programme de Parrainage",
    "referrals.description": "Invitez des amis et gagnez des récompenses ensemble ! Obtenez 50 points pour chaque ami qui rejoint, et ils reçoivent 25 points.",
    "referrals.totalReferrals": "Parrainages Totaux",
    "referrals.totalEarnings": "Gains Totaux",
    "referrals.rewardPerReferral": "Récompense par Parrainage",
    "referrals.yourCode": "Votre Code de Parrainage",
    "referrals.shareCode": "Partagez ce code avec vos amis pour gagner des récompenses",
    "referrals.copyLink": "Copier le Lien",
    "referrals.share": "Partager",
    "referrals.shareOnSocial": "Partager sur les réseaux sociaux",
    "referrals.howItWorks": "Comment ça marche :",
    "referrals.step1": "Partagez votre code de parrainage ou lien avec des amis",
    "referrals.step2": "Ils s'inscrivent en utilisant votre code et obtiennent 25 points bonus",
    "referrals.step3": "Vous recevez 50 points pour chaque parrainage réussi",
    "referrals.history": "Historique des Parrainages",
    "referrals.noReferrals": "Aucun parrainage encore",
    "referrals.startSharing": "Partagez votre code de parrainage pour commencer à gagner des récompenses !",
    "referrals.joined": "A rejoint",
    
    "common.loading": "Chargement...",
    "common.back": "Retour",
    "common.save": "Enregistrer",
    "common.cancel": "Annuler",
    "common.submit": "Soumettre",
    "common.edit": "Modifier",
    "common.delete": "Supprimer",
    "common.search": "Rechercher",
    "common.filter": "Filtrer",
    "common.sort": "Trier",
  },
  de: {
    "nav.home": "Startseite",
    "nav.challenges": "Herausforderungen",
    "nav.feed": "Feed",
    "nav.leaderboard": "Bestenliste",
    "nav.profile": "Profil",
    "nav.wallet": "Geldbörse",
    "nav.referrals": "Empfehlungen",
    "nav.admin": "Admin-Panel",
    "nav.signOut": "Abmelden",
    "nav.signIn": "Anmelden",
    "nav.getStarted": "Loslegen",
    
    "hero.badge": "Schließe dich 100k+ Kreativen weltweit an",
    "hero.title1": "Erstellen.",
    "hero.title2": "Konkurrieren.",
    "hero.title3": "Groß Gewinnen.",
    "hero.description": "Nimm an täglichen kreativen Herausforderungen teil, verdiene Punkte und Abzeichen, trete gegen Kreative weltweit an und gewinne echte Geldpreise. Deine Kreativität war noch nie so lohnend!",
    "hero.cta": "Jetzt Loslegen",
    "hero.howItWorks": "Wie es Funktioniert",
    "hero.prizesWon": "Gewonnene Preise",
    "hero.activeUsers": "Aktive Nutzer",
    "hero.challenges": "Herausforderungen",
    
    "stats.totalPrizes": "Gesamtpreise",
    "stats.awardedToCreators": "An Kreative vergeben",
    "stats.activeCreators": "Aktive Kreative",
    "stats.creatingDaily": "Täglich kreativ",
    "stats.dailyChallenges": "Tägliche Herausforderungen",
    "stats.newEveryDay": "Jeden Tag neu",
    "stats.avgEarnings": "Durchschnittl. Einnahmen",
    "stats.perMonth": "Pro Monat",
    
    "challenges.featured": "Empfohlene Herausforderungen",
    "challenges.trending": "Schließe dich diesen Trend-Herausforderungen an und beginne heute zu verdienen",
    "challenges.joinChallenge": "Herausforderung Beitreten",
    "challenges.participants": "Teilnehmer",
    "challenges.timeLeft": "Verbleibende Zeit",
    "challenges.prize": "Preis",
    "challenges.points": "Punkte",
    "challenges.difficulty": "Schwierigkeit",
    "challenges.easy": "Einfach",
    "challenges.medium": "Mittel",
    "challenges.hard": "Schwer",
    
    "cta.title": "Bereit, Deine Kreativität in Geld zu Verwandeln?",
    "cta.description": "Schließe dich Tausenden von Kreativen an, die Geld verdienen, indem sie das tun, was sie lieben. Melde dich jetzt an und erhalte 100 Bonuspunkte!",
    "cta.button": "Kostenlos bei Questify Mitmachen",
    
    "auth.login": "Anmelden",
    "auth.signup": "Registrieren",
    "auth.email": "E-Mail",
    "auth.password": "Passwort",
    "auth.username": "Benutzername",
    "auth.displayName": "Anzeigename (Optional)",
    "auth.signIn": "Einloggen",
    "auth.signInWith": "Oder fortfahren mit",
    "auth.createAccount": "Konto Erstellen",
    "auth.signingIn": "Anmeldung läuft...",
    "auth.creatingAccount": "Konto wird erstellt...",
    
    "referrals.title": "Empfehlungsprogramm",
    "referrals.description": "Lade Freunde ein und verdiene gemeinsam Belohnungen! Erhalte 50 Punkte für jeden Freund, der beitritt, und sie erhalten 25 Punkte.",
    "referrals.totalReferrals": "Gesamte Empfehlungen",
    "referrals.totalEarnings": "Gesamteinnahmen",
    "referrals.rewardPerReferral": "Belohnung pro Empfehlung",
    "referrals.yourCode": "Dein Empfehlungscode",
    "referrals.shareCode": "Teile diesen Code mit Freunden, um Belohnungen zu verdienen",
    "referrals.copyLink": "Link Kopieren",
    "referrals.share": "Teilen",
    "referrals.shareOnSocial": "In sozialen Medien teilen",
    "referrals.howItWorks": "So funktioniert's:",
    "referrals.step1": "Teile deinen Empfehlungscode oder Link mit Freunden",
    "referrals.step2": "Sie melden sich mit deinem Code an und erhalten 25 Bonuspunkte",
    "referrals.step3": "Du erhältst 50 Punkte für jede erfolgreiche Empfehlung",
    "referrals.history": "Empfehlungsverlauf",
    "referrals.noReferrals": "Noch keine Empfehlungen",
    "referrals.startSharing": "Teile deinen Empfehlungscode, um Belohnungen zu verdienen!",
    "referrals.joined": "Beigetreten",
    
    "common.loading": "Lädt...",
    "common.back": "Zurück",
    "common.save": "Speichern",
    "common.cancel": "Abbrechen",
    "common.submit": "Senden",
    "common.edit": "Bearbeiten",
    "common.delete": "Löschen",
    "common.search": "Suchen",
    "common.filter": "Filtern",
    "common.sort": "Sortieren",
  },
  pt: {
    "nav.home": "Início",
    "nav.challenges": "Desafios",
    "nav.feed": "Feed",
    "nav.leaderboard": "Classificação",
    "nav.profile": "Perfil",
    "nav.wallet": "Carteira",
    "nav.referrals": "Indicações",
    "nav.admin": "Painel Admin",
    "nav.signOut": "Sair",
    "nav.signIn": "Entrar",
    "nav.getStarted": "Começar",
    
    "hero.badge": "Junte-se a 100k+ Criadores Mundialmente",
    "hero.title1": "Criar.",
    "hero.title2": "Competir.",
    "hero.title3": "Ganhar Grande.",
    "hero.description": "Participe de desafios criativos diários, ganhe pontos e distintivos, compita com criadores do mundo todo e ganhe prêmios em dinheiro real. Sua criatividade nunca foi tão recompensadora!",
    "hero.cta": "Comece a Criar Agora",
    "hero.howItWorks": "Como Funciona",
    "hero.prizesWon": "Prêmios Ganhos",
    "hero.activeUsers": "Usuários Ativos",
    "hero.challenges": "Desafios",
    
    "stats.totalPrizes": "Prêmios Totais",
    "stats.awardedToCreators": "Concedidos a criadores",
    "stats.activeCreators": "Criadores Ativos",
    "stats.creatingDaily": "Criando diariamente",
    "stats.dailyChallenges": "Desafios Diários",
    "stats.newEveryDay": "Novos todos os dias",
    "stats.avgEarnings": "Ganhos Médios",
    "stats.perMonth": "Por mês",
    
    "challenges.featured": "Desafios em Destaque",
    "challenges.trending": "Participe destes desafios em alta e comece a ganhar hoje",
    "challenges.joinChallenge": "Participar do Desafio",
    "challenges.participants": "Participantes",
    "challenges.timeLeft": "Tempo Restante",
    "challenges.prize": "Prêmio",
    "challenges.points": "Pontos",
    "challenges.difficulty": "Dificuldade",
    "challenges.easy": "Fácil",
    "challenges.medium": "Médio",
    "challenges.hard": "Difícil",
    
    "cta.title": "Pronto para Transformar Sua Criatividade em Dinheiro?",
    "cta.description": "Junte-se a milhares de criadores ganhando dinheiro fazendo o que amam. Cadastre-se agora e ganhe 100 pontos de bônus!",
    "cta.button": "Entrar no Questify Grátis",
    
    "auth.login": "Entrar",
    "auth.signup": "Cadastrar",
    "auth.email": "Email",
    "auth.password": "Senha",
    "auth.username": "Nome de Usuário",
    "auth.displayName": "Nome de Exibição (Opcional)",
    "auth.signIn": "Fazer Login",
    "auth.signInWith": "Ou continuar com",
    "auth.createAccount": "Criar Conta",
    "auth.signingIn": "Entrando...",
    "auth.creatingAccount": "Criando conta...",
    
    "referrals.title": "Programa de Indicações",
    "referrals.description": "Convide amigos e ganhe recompensas juntos! Ganhe 50 pontos para cada amigo que se juntar, e eles ganham 25 pontos.",
    "referrals.totalReferrals": "Indicações Totais",
    "referrals.totalEarnings": "Ganhos Totais",
    "referrals.rewardPerReferral": "Recompensa por Indicação",
    "referrals.yourCode": "Seu Código de Indicação",
    "referrals.shareCode": "Compartilhe este código com amigos para ganhar recompensas",
    "referrals.copyLink": "Copiar Link",
    "referrals.share": "Compartilhar",
    "referrals.shareOnSocial": "Compartilhar nas redes sociais",
    "referrals.howItWorks": "Como funciona:",
    "referrals.step1": "Compartilhe seu código de indicação ou link com amigos",
    "referrals.step2": "Eles se cadastram usando seu código e ganham 25 pontos de bônus",
    "referrals.step3": "Você recebe 50 pontos para cada indicação bem-sucedida",
    "referrals.history": "Histórico de Indicações",
    "referrals.noReferrals": "Nenhuma indicação ainda",
    "referrals.startSharing": "Compartilhe seu código de indicação para começar a ganhar recompensas!",
    "referrals.joined": "Entrou em",
    
    "common.loading": "Carregando...",
    "common.back": "Voltar",
    "common.save": "Salvar",
    "common.cancel": "Cancelar",
    "common.submit": "Enviar",
    "common.edit": "Editar",
    "common.delete": "Excluir",
    "common.search": "Pesquisar",
    "common.filter": "Filtrar",
    "common.sort": "Ordenar",
  },
  it: {
    "nav.home": "Home",
    "nav.challenges": "Sfide",
    "nav.feed": "Feed",
    "nav.leaderboard": "Classifica",
    "nav.profile": "Profilo",
    "nav.wallet": "Portafoglio",
    "nav.referrals": "Referral",
    "nav.admin": "Pannello Admin",
    "nav.signOut": "Esci",
    "nav.signIn": "Accedi",
    "nav.getStarted": "Inizia",
    
    "hero.badge": "Unisciti a 100k+ Creatori in Tutto il Mondo",
    "hero.title1": "Crea.",
    "hero.title2": "Competi.",
    "hero.title3": "Vinci Alla Grande.",
    "hero.description": "Partecipa a sfide creative quotidiane, guadagna punti e badge, competi con creatori di tutto il mondo e vinci premi in denaro reale. La tua creatività non è mai stata così gratificante!",
    "hero.cta": "Inizia a Creare Ora",
    "hero.howItWorks": "Come Funziona",
    "hero.prizesWon": "Premi Vinti",
    "hero.activeUsers": "Utenti Attivi",
    "hero.challenges": "Sfide",
    
    "stats.totalPrizes": "Premi Totali",
    "stats.awardedToCreators": "Assegnati ai creatori",
    "stats.activeCreators": "Creatori Attivi",
    "stats.creatingDaily": "Creando quotidianamente",
    "stats.dailyChallenges": "Sfide Giornaliere",
    "stats.newEveryDay": "Nuove ogni giorno",
    "stats.avgEarnings": "Guadagni Medi",
    "stats.perMonth": "Al mese",
    
    "challenges.featured": "Sfide in Evidenza",
    "challenges.trending": "Unisciti a queste sfide di tendenza e inizia a guadagnare oggi",
    "challenges.joinChallenge": "Unisciti alla Sfida",
    "challenges.participants": "Partecipanti",
    "challenges.timeLeft": "Tempo Rimasto",
    "challenges.prize": "Premio",
    "challenges.points": "Punti",
    "challenges.difficulty": "Difficoltà",
    "challenges.easy": "Facile",
    "challenges.medium": "Medio",
    "challenges.hard": "Difficile",
    
    "cta.title": "Pronto a Trasformare la Tua Creatività in Denaro?",
    "cta.description": "Unisciti a migliaia di creatori che guadagnano facendo ciò che amano. Iscriviti ora e ottieni 100 punti bonus!",
    "cta.button": "Unisciti a Questify Gratis",
    
    "auth.login": "Accedi",
    "auth.signup": "Registrati",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.username": "Nome Utente",
    "auth.displayName": "Nome Visualizzato (Opzionale)",
    "auth.signIn": "Accedi",
    "auth.signInWith": "Oppure continua con",
    "auth.createAccount": "Crea Account",
    "auth.signingIn": "Accesso in corso...",
    "auth.creatingAccount": "Creazione account...",
    
    "referrals.title": "Programma Referral",
    "referrals.description": "Invita amici e guadagna premi insieme! Ottieni 50 punti per ogni amico che si unisce, e loro ricevono 25 punti.",
    "referrals.totalReferrals": "Referral Totali",
    "referrals.totalEarnings": "Guadagni Totali",
    "referrals.rewardPerReferral": "Ricompensa per Referral",
    "referrals.yourCode": "Il Tuo Codice Referral",
    "referrals.shareCode": "Condividi questo codice con gli amici per guadagnare premi",
    "referrals.copyLink": "Copia Link",
    "referrals.share": "Condividi",
    "referrals.shareOnSocial": "Condividi sui social media",
    "referrals.howItWorks": "Come funziona:",
    "referrals.step1": "Condividi il tuo codice o link referral con gli amici",
    "referrals.step2": "Si registrano usando il tuo codice e ottengono 25 punti bonus",
    "referrals.step3": "Ricevi 50 punti per ogni referral riuscito",
    "referrals.history": "Cronologia Referral",
    "referrals.noReferrals": "Nessun referral ancora",
    "referrals.startSharing": "Condividi il tuo codice referral per iniziare a guadagnare premi!",
    "referrals.joined": "Iscritto",
    
    "common.loading": "Caricamento...",
    "common.back": "Indietro",
    "common.save": "Salva",
    "common.cancel": "Annulla",
    "common.submit": "Invia",
    "common.edit": "Modifica",
    "common.delete": "Elimina",
    "common.search": "Cerca",
    "common.filter": "Filtra",
    "common.sort": "Ordina",
  },
  ja: {
    "nav.home": "ホーム",
    "nav.challenges": "チャレンジ",
    "nav.feed": "フィード",
    "nav.leaderboard": "リーダーボード",
    "nav.profile": "プロフィール",
    "nav.wallet": "ウォレット",
    "nav.referrals": "紹介",
    "nav.admin": "管理パネル",
    "nav.signOut": "ログアウト",
    "nav.signIn": "ログイン",
    "nav.getStarted": "始める",
    
    "hero.badge": "世界中の10万人以上のクリエイターに参加",
    "hero.title1": "作成。",
    "hero.title2": "競争。",
    "hero.title3": "大勝利。",
    "hero.description": "毎日のクリエイティブチャレンジに参加し、ポイントとバッジを獲得し、世界中のクリエイターと競い合い、本物の賞金を獲得しましょう。あなたの創造性がこれほどまでに報われることはありませんでした！",
    "hero.cta": "今すぐ作成を開始",
    "hero.howItWorks": "仕組み",
    "hero.prizesWon": "獲得賞金",
    "hero.activeUsers": "アクティブユーザー",
    "hero.challenges": "チャレンジ",
    
    "stats.totalPrizes": "総賞金",
    "stats.awardedToCreators": "クリエイターに授与",
    "stats.activeCreators": "アクティブクリエイター",
    "stats.creatingDaily": "毎日作成",
    "stats.dailyChallenges": "デイリーチャレンジ",
    "stats.newEveryDay": "毎日新しい",
    "stats.avgEarnings": "平均収益",
    "stats.perMonth": "月間",
    
    "challenges.featured": "注目のチャレンジ",
    "challenges.trending": "これらのトレンドチャレンジに参加して、今日から稼ぎましょう",
    "challenges.joinChallenge": "チャレンジに参加",
    "challenges.participants": "参加者",
    "challenges.timeLeft": "残り時間",
    "challenges.prize": "賞品",
    "challenges.points": "ポイント",
    "challenges.difficulty": "難易度",
    "challenges.easy": "簡単",
    "challenges.medium": "普通",
    "challenges.hard": "難しい",
    
    "cta.title": "創造性をお金に変える準備はできましたか？",
    "cta.description": "好きなことをしてお金を稼いでいる何千ものクリエイターに参加しましょう。今すぐサインアップして100ボーナスポイントを獲得！",
    "cta.button": "Questifyに無料参加",
    
    "auth.login": "ログイン",
    "auth.signup": "サインアップ",
    "auth.email": "メール",
    "auth.password": "パスワード",
    "auth.username": "ユーザー名",
    "auth.displayName": "表示名（オプション）",
    "auth.signIn": "サインイン",
    "auth.signInWith": "または続行",
    "auth.createAccount": "アカウント作成",
    "auth.signingIn": "サインイン中...",
    "auth.creatingAccount": "アカウント作成中...",
    
    "referrals.title": "紹介プログラム",
    "referrals.description": "友達を招待して一緒に報酬を獲得しましょう！参加した友達1人につき50ポイント獲得し、彼らは25ポイント獲得します。",
    "referrals.totalReferrals": "総紹介数",
    "referrals.totalEarnings": "総収益",
    "referrals.rewardPerReferral": "紹介ごとの報酬",
    "referrals.yourCode": "あなたの紹介コード",
    "referrals.shareCode": "このコードを友達と共有して報酬を獲得",
    "referrals.copyLink": "リンクをコピー",
    "referrals.share": "共有",
    "referrals.shareOnSocial": "ソーシャルメディアで共有",
    "referrals.howItWorks": "仕組み：",
    "referrals.step1": "紹介コードまたはリンクを友達と共有",
    "referrals.step2": "彼らがあなたのコードを使用してサインアップし、25ボーナスポイント獲得",
    "referrals.step3": "成功した紹介ごとに50ポイント獲得",
    "referrals.history": "紹介履歴",
    "referrals.noReferrals": "まだ紹介はありません",
    "referrals.startSharing": "紹介コードを共有して報酬を獲得しましょう！",
    "referrals.joined": "参加日",
    
    "common.loading": "読み込み中...",
    "common.back": "戻る",
    "common.save": "保存",
    "common.cancel": "キャンセル",
    "common.submit": "送信",
    "common.edit": "編集",
    "common.delete": "削除",
    "common.search": "検索",
    "common.filter": "フィルター",
    "common.sort": "並び替え",
  },
  ko: {
    "nav.home": "홈",
    "nav.challenges": "챌린지",
    "nav.feed": "피드",
    "nav.leaderboard": "리더보드",
    "nav.profile": "프로필",
    "nav.wallet": "지갑",
    "nav.referrals": "추천",
    "nav.admin": "관리자 패널",
    "nav.signOut": "로그아웃",
    "nav.signIn": "로그인",
    "nav.getStarted": "시작하기",
    
    "hero.badge": "전 세계 10만 명 이상의 크리에이터와 함께하세요",
    "hero.title1": "창작.",
    "hero.title2": "경쟁.",
    "hero.title3": "큰 승리.",
    "hero.description": "일일 창의적 챌린지에 참여하고, 포인트와 배지를 획득하며, 전 세계 크리에이터들과 경쟁하고, 실제 현금 상금을 받으세요. 당신의 창의성이 이렇게 보람 있었던 적이 없었습니다!",
    "hero.cta": "지금 창작 시작",
    "hero.howItWorks": "작동 방식",
    "hero.prizesWon": "획득한 상금",
    "hero.activeUsers": "활성 사용자",
    "hero.challenges": "챌린지",
    
    "stats.totalPrizes": "총 상금",
    "stats.awardedToCreators": "크리에이터에게 수여",
    "stats.activeCreators": "활성 크리에이터",
    "stats.creatingDaily": "매일 창작",
    "stats.dailyChallenges": "일일 챌린지",
    "stats.newEveryDay": "매일 새로운",
    "stats.avgEarnings": "평균 수익",
    "stats.perMonth": "월간",
    
    "challenges.featured": "추천 챌린지",
    "challenges.trending": "이 트렌딩 챌린지에 참여하고 오늘부터 수익을 얻으세요",
    "challenges.joinChallenge": "챌린지 참여",
    "challenges.participants": "참가자",
    "challenges.timeLeft": "남은 시간",
    "challenges.prize": "상금",
    "challenges.points": "포인트",
    "challenges.difficulty": "난이도",
    "challenges.easy": "쉬움",
    "challenges.medium": "보통",
    "challenges.hard": "어려움",
    
    "cta.title": "창의성을 현금으로 바꿀 준비가 되셨나요?",
    "cta.description": "좋아하는 일을 하면서 돈을 버는 수천 명의 크리에이터와 함께하세요. 지금 가입하고 100 보너스 포인트를 받으세요!",
    "cta.button": "Questify 무료 가입",
    
    "auth.login": "로그인",
    "auth.signup": "회원가입",
    "auth.email": "이메일",
    "auth.password": "비밀번호",
    "auth.username": "사용자 이름",
    "auth.displayName": "표시 이름 (선택사항)",
    "auth.signIn": "로그인",
    "auth.signInWith": "또는 계속",
    "auth.createAccount": "계정 만들기",
    "auth.signingIn": "로그인 중...",
    "auth.creatingAccount": "계정 생성 중...",
    
    "referrals.title": "추천 프로그램",
    "referrals.description": "친구를 초대하고 함께 보상을 받으세요! 가입한 친구 1명당 50포인트를 받고, 그들은 25포인트를 받습니다.",
    "referrals.totalReferrals": "총 추천 수",
    "referrals.totalEarnings": "총 수익",
    "referrals.rewardPerReferral": "추천당 보상",
    "referrals.yourCode": "내 추천 코드",
    "referrals.shareCode": "이 코드를 친구와 공유하여 보상을 받으세요",
    "referrals.copyLink": "링크 복사",
    "referrals.share": "공유",
    "referrals.shareOnSocial": "소셜 미디어에 공유",
    "referrals.howItWorks": "작동 방식:",
    "referrals.step1": "추천 코드나 링크를 친구와 공유",
    "referrals.step2": "그들이 코드로 가입하고 25 보너스 포인트 획득",
    "referrals.step3": "성공한 추천마다 50포인트 획득",
    "referrals.history": "추천 기록",
    "referrals.noReferrals": "아직 추천 없음",
    "referrals.startSharing": "추천 코드를 공유하여 보상을 받으세요!",
    "referrals.joined": "가입일",
    
    "common.loading": "로딩 중...",
    "common.back": "뒤로",
    "common.save": "저장",
    "common.cancel": "취소",
    "common.submit": "제출",
    "common.edit": "편집",
    "common.delete": "삭제",
    "common.search": "검색",
    "common.filter": "필터",
    "common.sort": "정렬",
  },
  zh: {
    "nav.home": "首页",
    "nav.challenges": "挑战",
    "nav.feed": "动态",
    "nav.leaderboard": "排行榜",
    "nav.profile": "个人资料",
    "nav.wallet": "钱包",
    "nav.referrals": "推荐",
    "nav.admin": "管理面板",
    "nav.signOut": "登出",
    "nav.signIn": "登录",
    "nav.getStarted": "开始",
    
    "hero.badge": "加入全球10万多名创作者",
    "hero.title1": "创作。",
    "hero.title2": "竞争。",
    "hero.title3": "赢大奖。",
    "hero.description": "参加每日创意挑战，赚取积分和徽章，与全球创作者竞争，赢取真实现金奖励。你的创造力从未如此有价值！",
    "hero.cta": "立即开始创作",
    "hero.howItWorks": "如何运作",
    "hero.prizesWon": "已获奖金",
    "hero.activeUsers": "活跃用户",
    "hero.challenges": "挑战",
    
    "stats.totalPrizes": "总奖金",
    "stats.awardedToCreators": "授予创作者",
    "stats.activeCreators": "活跃创作者",
    "stats.creatingDaily": "每日创作",
    "stats.dailyChallenges": "每日挑战",
    "stats.newEveryDay": "每天更新",
    "stats.avgEarnings": "平均收益",
    "stats.perMonth": "每月",
    
    "challenges.featured": "精选挑战",
    "challenges.trending": "加入这些热门挑战，今天就开始赚钱",
    "challenges.joinChallenge": "加入挑战",
    "challenges.participants": "参与者",
    "challenges.timeLeft": "剩余时间",
    "challenges.prize": "奖金",
    "challenges.points": "积分",
    "challenges.difficulty": "难度",
    "challenges.easy": "简单",
    "challenges.medium": "中等",
    "challenges.hard": "困难",
    
    "cta.title": "准备好把创造力变成现金了吗？",
    "cta.description": "加入数千名通过做自己喜欢的事赚钱的创作者。立即注册并获得100积分奖励！",
    "cta.button": "免费加入Questify",
    
    "auth.login": "登录",
    "auth.signup": "注册",
    "auth.email": "邮箱",
    "auth.password": "密码",
    "auth.username": "用户名",
    "auth.displayName": "显示名称（可选）",
    "auth.signIn": "登录",
    "auth.signInWith": "或继续使用",
    "auth.createAccount": "创建账户",
    "auth.signingIn": "登录中...",
    "auth.creatingAccount": "创建账户中...",
    
    "referrals.title": "推荐计划",
    "referrals.description": "邀请朋友，一起赚取奖励！每邀请一位朋友加入获得50积分，他们获得25积分。",
    "referrals.totalReferrals": "总推荐数",
    "referrals.totalEarnings": "总收益",
    "referrals.rewardPerReferral": "每次推荐奖励",
    "referrals.yourCode": "你的推荐码",
    "referrals.shareCode": "与朋友分享此代码以赚取奖励",
    "referrals.copyLink": "复制链接",
    "referrals.share": "分享",
    "referrals.shareOnSocial": "在社交媒体上分享",
    "referrals.howItWorks": "如何运作：",
    "referrals.step1": "与朋友分享你的推荐码或链接",
    "referrals.step2": "他们使用你的代码注册并获得25积分奖励",
    "referrals.step3": "每成功推荐一人，你获得50积分",
    "referrals.history": "推荐历史",
    "referrals.noReferrals": "暂无推荐",
    "referrals.startSharing": "分享你的推荐码开始赚取奖励！",
    "referrals.joined": "加入于",
    
    "common.loading": "加载中...",
    "common.back": "返回",
    "common.save": "保存",
    "common.cancel": "取消",
    "common.submit": "提交",
    "common.edit": "编辑",
    "common.delete": "删除",
    "common.search": "搜索",
    "common.filter": "筛选",
    "common.sort": "排序",
  },
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("questify-language");
    return (saved as Language) || "en";
  });

  useEffect(() => {
    localStorage.setItem("questify-language", language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: setLanguageState, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
