import { Header } from "@/components/Header";
import { Card } from "@/components/ui/card";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { Button } from "@/components/ui/button";
import { ArrowLeft, HelpCircle, Trophy, Camera, Star, Wallet, Users, Shield } from "lucide-react";
import { useNavigate } from "react-router-dom";

const FAQ = () => {
  const navigate = useNavigate();

  const faqs = [
    {
      category: "How It Works",
      icon: HelpCircle,
      questions: [
        {
          q: "What is Questify?",
          a: "Questify is a creative challenge platform where you can participate in photo and video challenges to win real cash prizes! New challenges are automatically generated for you every day."
        },
        {
          q: "How do I participate in a challenge?",
          a: "It's simple! Click on a challenge you like, take an original photo or video that matches the theme, add a caption if you want, and submit. You can edit your image with filters and stickers before posting."
        },
        {
          q: "Who creates the challenges?",
          a: "Challenges are automatically generated by our AI to ensure fresh and trendy content every day. Admins can also create special or sponsored challenges."
        },
      ]
    },
    {
      category: "Winning & Prizes",
      icon: Trophy,
      questions: [
        {
          q: "How do I win a challenge?",
          a: "At the end of each challenge, participants are ranked by votes (likes) and positive comments. The top 10 share the prizes! The more likes and positive comments you get, the higher you rank."
        },
        {
          q: "What are the prizes?",
          a: "Each challenge displays its prize (e.g., $500 Cash). Winners receive their winnings directly in their Questify wallet, which they can then withdraw."
        },
        {
          q: "What are points for?",
          a: "Points you earn by participating in challenges increase your level and unlock badges. The more you participate, the higher your level!"
        },
      ]
    },
    {
      category: "Submissions",
      icon: Camera,
      questions: [
        {
          q: "What types of content can I submit?",
          a: "You can submit photos or videos depending on the challenge type. Make sure your content is original and matches the challenge theme."
        },
        {
          q: "Why was my submission rejected?",
          a: "Submissions are automatically verified. If your image appears to be AI-generated or taken from the internet, it will be rejected. Only original photos/videos that YOU created are accepted."
        },
        {
          q: "Can I edit my submission?",
          a: "Once submitted, you cannot modify your entry. Make sure everything is perfect before submitting!"
        },
      ]
    },
    {
      category: "Leaderboard & Ranking",
      icon: Star,
      questions: [
        {
          q: "How does the leaderboard work?",
          a: "The leaderboard displays the Top 10 participants for each completed challenge. Ranking is based on: Likes × 2 + Comments. You can also see your own rank."
        },
        {
          q: "When is the ranking finalized?",
          a: "The final ranking is determined at the end of the challenge (when time runs out). Prizes are then distributed to the winners."
        },
      ]
    },
    {
      category: "Wallet & Payments",
      icon: Wallet,
      questions: [
        {
          q: "How do I withdraw my winnings?",
          a: "Go to your Wallet, check your balance, and click 'Withdraw'. Payments are processed through our secure system."
        },
        {
          q: "When will I receive my winnings?",
          a: "Winnings from completed challenges are automatically credited to your wallet. Withdrawals are processed within 3-5 business days."
        },
      ]
    },
    {
      category: "Community",
      icon: Users,
      questions: [
        {
          q: "How do I follow other creators?",
          a: "Click on a creator's profile and press 'Follow'. You'll then see their submissions in your 'Following' feed."
        },
        {
          q: "How do I earn referral rewards?",
          a: "Share your unique referral link (in the Referrals section). When someone signs up with your link, you earn rewards!"
        },
      ]
    },
    {
      category: "Rules & Safety",
      icon: Shield,
      questions: [
        {
          q: "What are the main rules?",
          a: "1. Original content only (no AI, no internet). 2. Follow the challenge theme. 3. No offensive or inappropriate content. 4. One account per person."
        },
        {
          q: "How is fraud detected?",
          a: "Our AI automatically verifies each submission to detect AI-generated images or ones taken from the internet. Cheaters are banned."
        },
      ]
    },
  ];

  return (
    <div className="min-h-screen bg-background">
      <Header />

      <div className="container py-8 space-y-8">
        <div className="flex items-center gap-4">
          <Button variant="ghost" onClick={() => navigate(-1)} className="gap-2">
            <ArrowLeft className="w-4 h-4" />
            Back
          </Button>
        </div>

        <div className="text-center space-y-4">
          <h1 className="text-4xl md:text-5xl font-bold">
            Frequently Asked Questions
          </h1>
          <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
            Everything you need to know to become a Questify pro!
          </p>
        </div>

        <div className="grid gap-6 md:grid-cols-2">
          {faqs.map((category, categoryIndex) => (
            <Card key={categoryIndex} className="p-6">
              <div className="flex items-center gap-3 mb-4">
                <div className="p-2 rounded-lg bg-primary/10">
                  <category.icon className="w-5 h-5 text-primary" />
                </div>
                <h2 className="text-xl font-bold">{category.category}</h2>
              </div>
              
              <Accordion type="single" collapsible className="w-full">
                {category.questions.map((faq, faqIndex) => (
                  <AccordionItem key={faqIndex} value={`item-${categoryIndex}-${faqIndex}`}>
                    <AccordionTrigger className="text-left">
                      {faq.q}
                    </AccordionTrigger>
                    <AccordionContent className="text-muted-foreground">
                      {faq.a}
                    </AccordionContent>
                  </AccordionItem>
                ))}
              </Accordion>
            </Card>
          ))}
        </div>

        <Card className="p-8 text-center bg-gradient-to-r from-primary/10 to-accent/10">
          <h2 className="text-2xl font-bold mb-4">
            Still have questions?
          </h2>
          <p className="text-muted-foreground mb-6">
            Our team is here to help! Contact us by email.
          </p>
          <Button 
            size="lg" 
            className="bg-gradient-primary"
            onClick={() => window.location.href = 'mailto:support@questify.app'}
          >
            Contact Us
          </Button>
        </Card>
      </div>
    </div>
  );
};

export default FAQ;