// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';

// These are public browser credentials, not server secrets. Keep production
// usable if a hosting environment is rebuilt before its VITE variables are set.
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL
  || "https://wfaeptwxocikjumzwddu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY
  || "sb_publishable_NrBMNxPzih1Rqt0xXla-yQ_yx_7x0S5";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: brokeredPreviewStorage(),
    persistSession: true,
    autoRefreshToken: true,
  }
});
